### ISSUE TITLE
Futures consult dont match with wallet balance

### ISSUE THREAD

**Issue by luccosta** [binance/binance-connector-python#103]
I'm trying to use Spot with Futures module to consult USER_DATA, but the data I get from the API (almost all NULL results), dont match with the wallet balances that I see in Binance. 

I'm using the following code:

from binance.spot import Spot as Client

client.futures_loan_liquidation_history(collateralCoin="BTC")
client.futures_loan_repay_history(coin="USDTPERP")
client.futures_loan_configs(collateralCoin="BTC")
client.futures_loan_adjust_collateral_history(collateralCoin="BTC")
client.futures_loan_borrow_history(coin="USDTPERP")
client.futures_loan_interest_history()

And the output: 

{'total': 0, 'rows': []}
{'total': 0, 'rows': []}
[{'collateralCoin': 'BTC', 'rate': '0.65', 'marginCallCollateralRate': '0.8', 'liquidationCollateralRate': '0.9', 'currentCollateralRate': '0', 'interestRate': '0.0024', 'interestGracePeriod': '2', 'loanCoin': 'USDT'}, {'collateralCoin': 'BTC', 'rate': '0.65', 'marginCallCollateralRate': '0.8', 'liquidationCollateralRate': '0.9', 'currentCollateralRate': '0', 'interestRate': '0.0024', 'interestGracePeriod': '2', 'loanCoin': 'BUSD'}]
{'total': 0, 'rows': []}
{'total': 0, 'rows': []}
{'total': 0, 'rows': []}

* Version of binance-connector-python: 1.5.0
* Python version: 3.6.9
* Operating system: Ubuntu 18.04

**Comment by luccosta** [comment]
If there is no way through the connector someone can recommend another way.

**Comment by aisling11** [comment]
Hi @luccosta, this doesn't seem to be not related with the connector but with the account you're using with the connector.

Are you sure, you're associating an API Key that has done relevant activities on the Futures product to lead the need to receive non null responses? For example: Did your ever receive liquidation? It's working as normally on my side.

(Note: "USDTPERP" is not a valid coin )

**Comment by 2pd** [comment]
this connector library is not for futures account/trading.   
These data can be found from /fapi/*,  however it's not implemented in this library.
