### ISSUE TITLE
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)

### ISSUE THREAD

**Issue by Japheth007** [binance/binance-connector-python#104]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)

### Expected behaviour
Describe what should happen.

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python   1.6.0
* Python version  Python 3.7.9
* Operating system window 10 X64 familly

**Comment by Japheth007** [comment]
need some help

**Comment by 2pd** [comment]
We found there may be some glitch on windows to build a SSL connection,  the client may not get the ssh certification file correctly, please check this issue and see if it helps
https://github.com/binance/binance-connector-python/issues/57

**Comment by aisling11** [comment]
Hi @Japheth007, didn't received further updates on this so closing this issue for now, but feel free to re-open if you have  new questions.
