### ISSUE TITLE
Use own logger for module

### ISSUE THREAD

**Issue by auchri** [binance/binance-connector-python#105]
Hi,

can you please use a own logger for your module and not write to the default logger?
Like it is described here: https://stackoverflow.com/a/15735146

### Expected behaviour
```py
import logging
...
logger = logging.getLogger(__name__)
...
logger.debug("raw response from server:" + response.text)
```

### Actual behaviour
```py
import logging
......
logging.debug("raw response from server:" + response.text)
```

**Comment by aisling11** [comment]
We'll include this in the upcoming release. Thx.
