### ISSUE TITLE
Delay Binance

### ISSUE THREAD

**Issue by VuzzyM** [binance/binance-connector-python#110]
Hello @2pd @aisling11 

The problem is in the 5 minute delay.
I need to make a scraper that can find the currency fixed, without delaying the listing on the website by 5 minutes, is it possible somehow?

https://stackoverflow.com/questions/67736951/beautiful-soup-web-scraper-on-binance-announcement-page-lags-behind-by-5-minutes

Other coin listed recently with delay 5 minutes: 

![chesstime](https://user-images.githubusercontent.com/66425682/139838380-3a4ff326-b3f2-4cb6-a260-57a393b51f5e.png)
![Screenshot-7-1024x576](https://user-images.githubusercontent.com/66425682/139838382-48058add-10e8-4609-a9f5-3adf1a9457c6.png)

Coin Chess the announcement has been announced on 3:36. But 5 minutes before it started buying massively on other platforms.

**Comment by VuzzyM** [comment]
@2pd @aisling11 Is there a solution?

**Comment by aisling11** [comment]
Hi @VuzzyM, the mechanism behind Binance announcements posts are beyond what this project is about (we focus on https://binance-docs.github.io/apidocs/spot/en/#change-log only), so unfortunately we don't have suggestions.
