### ISSUE TITLE
Wrong logging.basicConfig params for Windows platform

### ISSUE THREAD

**Issue by DMirella** [binance/binance-connector-python#112]
### Issue subject
If user tries to build first example from readme git file on windows platform then it fails due to strftime is not maintain %s format. https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior 
I've fixed this with changing file binance\lib\utils.py line 79:  changed to datefmt="%Y-%m-%d %H:%M:%S.".(remove %s)

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python: latest on 2021-11-07
* Python version: 3.10
* Operating system: Windows 10

**Comment by aisling11** [comment]
Hi @DMirella, is https://github.com/binance/binance-connector-python/blob/master/examples/spot/blvt/blvt_info.py the example you're referring to?  And could also share the failure message with us please? 

The `%s` is logging's standard string substitution which should help to log the time in timestamp format.

**Comment by DMirella** [comment]
Yes. 
> The %s is logging's standard string substitution which should help to log the time in timestamp format.
In ticket description I've attached link where I can't see %s as possible format param.

Here the error:
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\DMirella\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1098, in emit
    msg = self.format(record)
  File "C:\Users\DMirella\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 942, in format
    return fmt.format(record)
  File "C:\Users\DMirella\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 680, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "C:\Users\DMirella\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 617, in formatTime
    s = time.strftime(datefmt, ct)
ValueError: Invalid format string
Call stack:
  File "C:\Users\DMirella\PycharmProjects\pythonProject\main.py", line 15, in <module>
    logging.info(spot_client.historical_trades("BTCUSDT", limit=10))
Message: [{'id': 1137709573, 'price': '67227.78000000', 'qty': '0.00024000', 'quoteQty': '16.13466720', 'time': 1636490801400, 'isBuyerMaker': True, 'isBestMatch': True}, {'id': 1137709574, 'price': '67227.79000000', 'qty': '0.03580000', 'quoteQty': '2406.75488200', 'time': 1636490801468, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 1137709575, 'price': '67227.79000000', 'qty': '0.00183000', 'quoteQty': '123.02685570', 'time': 1636490801672, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 1137709576, 'price': '67227.79000000', 'qty': '0.10000000', 'quoteQty': '6722.77900000', 'time': 1636490801721, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 1137709577, 'price': '67227.78000000', 'qty': '0.00004000', 'quoteQty': '2.68911120', 'time': 1636490801788, 'isBuyerMaker': True, 'isBestMatch': True}, {'id': 1137709578, 'price': '67227.78000000', 'qty': '0.00326000', 'quoteQty': '219.16256280', 'time': 1636490801788, 'isBuyerMaker': True, 'isBestMatch': True}, {'id': 1137709579, 'price': '67230.42000000', 'qty': '0.01606000', 'quoteQty': '1079.72054520', 'time': 1636490802065, 'isBuyerMaker': True, 'isBestMatch': True}, {'id': 1137709580, 'price': '67230.43000000', 'qty': '0.00030000', 'quoteQty': '20.16912900', 'time': 1636490802075, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 1137709581, 'price': '67230.43000000', 'qty': '0.00005000', 'quoteQty': '3.36152150', 'time': 1636490802111, 'isBuyerMaker': False, 'isBestMatch': True}, {'id': 1137709582, 'price': '67233.92000000', 'qty': '0.00010000', 'quoteQty': '6.72339200', 'time': 1636490802111, 'isBuyerMaker': False, 'isBestMatch': True}]
Arguments: ()

Process finished with exit code 0

**Comment by aisling11** [comment]
Thank you @DMirella, we'll remove `%s` (and consequently no timestamp) in the next release.
