### ISSUE TITLE
Timestamp out of recvWindow when pinging test api.

### ISSUE THREAD

**Issue by blakat360** [binance/binance-connector-python#119]
### issue subject
Running the example code on the test api leads to a ```Timestamp for this request is outside of the recvWindow``` error.

### repro
``` py
from binance.spot import Spot 

client = Spot()
print(client.time())

client = Spot(base_url='https://testnet.binance.vision', key='<api_key>', secret='<api_secret>')

# Get account information
print(client.account()) # error here
```

I have also tried passing a timestamp (sourced from ```client.time()['serverTime']```) and setting ```recvWindow=60000```, to no avail.

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python - binance-connector==1.8.0
* Python version - Python 3.9.9
* Operating system -  x86_64 GNU/Linux, (5.10.83-1-MANJARO )

**Comment by aisling11** [comment]
Hey @blakat360, can you share the code where you do: "passing a timestamp (sourced from client.time()['serverTime']) and setting recvWindow=60000?" 

You can also try to change your local machine's time to be same as GET /api/v3/time instead of changing the timestamp.

More info: https://dev.binance.vision/t/error-timestamp-for-this-request-is-outside-of-the-recvwindow/1357

**Comment by aisling11** [comment]
Hey @blakat360, closing the issue for now as we haven't seen new comments, but please feel free to reopen if you have anything extra to add on.

**Comment by blakat360** [comment]
```py
```

**Comment by aisling11** [comment]
@blakat360 You don't have to send timestamp parameter, binance-connector-python already generates it automatically when you use the account() method. To see params you can insert, see https://github.com/binance/binance-connector-python/blob/master/binance/spot/account.py#L318.

**Comment by 2pd** [comment]
```python

print(client.account(ecvWindow=60000))

```

this should work, otherwise please align the local time.

**Comment by blakat360** [comment]
How do I align the local time?
