### ISSUE TITLE
Avoid pinning specific dependency versions

### ISSUE THREAD

**Issue by aliask** [binance/binance-connector-python#120]
### Issue subject
Dependencies are specified in `requirements/*.txt` with `==` versioning ([example](https://github.com/binance/binance-connector-python/blob/master/requirements/common.txt#L4)), against Python's best-practice guidance [here](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/).

This can cause conflicts in projects which have incompatible version requirements

### Expected behaviour
Module dependencies should be as unrestrictive as possible. 
If no known incompatibilities exist, then simply specify the package name, or if certain versions are known to be incompatible then use `A>=1,<2` style versioning.

### Actual behaviour
Dependencies are pinned to specific versions.

### Steps to reproduce
N/A

### Environment
N/A

**Comment by aisling11** [comment]
Thank you @aliask, we'll update this in the next version.
