### ISSUE TITLE
websocket如何获取合并精度的市场深度？

### ISSUE THREAD

**Issue by Legend94rz** [binance/binance-connector-python#122]
例如想获取精度分别为0.1 / 1 / 10的有限档市场深度，应该怎么做？
现有的api似乎无法指定精度，比如订阅btcusdt@depth20，只能拿到20档，精确到0.01的深度，似乎不能取精确到10的深度。

**Comment by aisling11** [comment]
嗨 @Legend94rz  Websocket 不支持不同的精度选择 （请看[文档](https://binance-docs.github.io/apidocs/spot/en/#partial-book-depth-streams)），你应该可以在本地做转换。
