### ISSUE TITLE
limit order 

### ISSUE THREAD

**Issue by hsh0107** [binance/binance-connector-python#129]
我有一个限价单， 部分成交， 那么撤销该限价单， 那么成交的部分会撤销吗？ 那位表弟给解释一下

**Comment by chairz** [comment]
成交那笔不会被撤

**Comment by hsh0107** [comment]
> 成交那笔不会被撤
看见Contributor 会中文 我激动的热泪盈眶， 我还有一个问题，通过create_order 创建一个市价单， 会立即成交吗？还是说等待成交

**Comment by 2pd** [comment]
你可以到dev.binance.vision提交API相关的问题。
