### ISSUE TITLE
Websocket for margin accounts

### ISSUE THREAD

**Issue by sha256-mercury** [binance/binance-connector-python#135]
### Feature request
Websocket features for Margin (Cross and Isolated) accounts seem to not be implemented

### Expected behaviour
Listen to events from margin accounts like orders state update, etc. It can be classify as a 

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python
* Python version
* ALL

**Comment by 2pd** [comment]
Get the margin account listen key via `new_margin_listen_key`, then listen to the stream with method `user_data`.

**Comment by sha256-mercury** [comment]
Thank you @2pd .

**Comment by 2pd** [comment]
no worries :)
