### ISSUE TITLE
Cannot find reference 'callFromThread' in 'reactor.py' 

### ISSUE THREAD

**Issue by harper1999** [binance/binance-connector-python#138]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.
刚下的websocket sdk, binance_socket_manager模块下的reactor.callFromThread方法读不到 Cannot find reference 'callFromThread' in 'reactor.py' 
还有导入库也报错Package containing module 'twisted' is not listed in the project requirements
已经pip install -r requirements/requirements.txt

### Expected behaviour
Describe what should happen.

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python  
* Python version   3.9
* Operating system  windows11

**Comment by pongit** [comment]
hi

**Comment by aisling-2** [comment]
@harper1999 请问后来解决问题了吗？如果还需要答案的话，请提供更多信息。
“Steps to reproduce” 这一步很重要，不提供我们这边很难理解全体情况。

**Comment by aisling-2** [comment]
I'm closing this, due to lack of response.
