### ISSUE TITLE
Margin TAKE_PROFIT Order - Unknown Error

### ISSUE THREAD

**Issue by Ocma** [binance/binance-connector-python#139]
Hi there, I would appreciate your help with an issue that I have been trying to solve for a bit but can't get my head around, and I have not seen any other Issue about this in this project.

### Issue subject
I managed to open a margin order using for example `side = 'BUY', type='MARKET' and sideEffectType='MARGIN_BUY'`.
```
client.new_margin_order(symbol = coin,
                        side = 'BUY',
                        type = 'MARKET',
                        sideEffectType='MARGIN_BUY',
                        newOrderRespType='FULL',
                        quantity=qty_order
                        )
```
The issue comes when I try to close and repay that order. I am using `side = 'SELL', type='TAKE_PROFIT', sideEffectType = 'AUTO_REPAY'`

```
client.new_margin_order(symbol = coin,
                       side = 'SELL',
                       type =  'TAKE_PROFIT,
                       stopPrice = stopPrice,
                       quantity=qty_order,
                       sideEffectType = 'AUTO_REPAY',
                       newOrderRespType = 'FULL'
                       )
```
stopPrice, in this example, will be higher than the price I entered the first order.
The quantity in both order is the same.

### Expected behaviour
I am expecting to create an open position which will sell the same quantity I bought in the first order, when a certain price has been reached (in this case at a take profit level). At the same time it repays any money 'borrowed' (using 'Auto_repay') when the first order was placed.

### Actual behaviour
Instead I am getting a 'Unknown Error':

`ServerError: (500, '{"code":-1000,"msg":"An unknown error occurred while processing the request."}')`

I will paste the Traceback:

```
ServerError                               Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 client.new_margin_order(
      2                             symbol = coin,
      3                             side = 'SELL',
      4                             type =  'TAKE_PROFIT',
      5                             stopPrice = stopPrice,
      6                             quantity=qty_order,
      7                              sideEffectType = 'AUTO_REPAY',
      8                              newOrderRespType = 'FULL'
      9                                      )

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/binance/spot/margin.py:187, in new_margin_order(self, symbol, side, type, **kwargs)
    178 check_required_parameters(
    179     [
    180         [symbol, "symbol"],
   (...)
    183     ]
    184 )
    186 payload = {"symbol": symbol, "side": side, "type": type, **kwargs}
--> 187 return self.sign_request("POST", "/sapi/v1/margin/order", payload)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/binance/api.py:83, in API.sign_request(self, http_method, url_path, payload)
     81 signature = self._get_sign(query_string)
     82 payload["signature"] = signature
---> 83 return self.send_request(http_method, url_path, payload)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/binance/api.py:117, in API.send_request(self, http_method, url_path, payload)
    115 response = self._dispatch_request(http_method)(**params)
    116 self._logger.debug("raw response from server:" + response.text)
--> 117 self._handle_exception(response)
    119 try:
    120     data = response.json()

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/binance/api.py:171, in API._handle_exception(self, response)
    169         raise ClientError(status_code, None, response.text, response.headers)
    170     raise ClientError(status_code, err["code"], err["msg"], response.headers)
--> 171 raise ServerError(status_code, response.text)

ServerError: (500, '{"code":-1000,"msg":"An unknown error occurred while processing the request."}')
```

### Steps to reproduce
Create a margin market order using `sideEffectType='MARGIN_BUY'` and create a TAKE_PROFIT order, in the opposite direction, using `sideEffectType = 'AUTO_REPAY'`

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python == 1.12 (I am using binance-connector not binance-connector-python, I believe is the same?)
* Python version == 3.9.12
* Operating system == MacOS Catalina

**Comment by 2pd** [comment]
Thanks for your feedback,  we can reproduce the issue. This is not an issue from this library, but the error message should be improved from API side. It has been shared with team, hope it will be fixed soon.

**Comment by Ocma** [comment]
Ok! I will keep looking at what is triggering the error then... Thanks a lot for the quick response!

**Comment by 2pd** [comment]
`TAKE_PROFIT` is not supported in the margin symbols,  you may wish to try `TAKE_PROFIT_LIMIT`.  The error message may need to be improved, but it's not the issue of this library.
I'm going to close this issue.
