### ISSUE TITLE
Missing documentation for Account / Trade Endpoints

### ISSUE THREAD

**Issue by alper-maker** [binance/binance-connector-python#141]
Hello,

Readthedocs does not mention about "Account / Trade Endpoints" on SPOT APIs list. [See SPOT APIs list](https://binance-connector.readthedocs.io/en/stable/binance.spot.html), there is no link to Account endpoints currently.

[Searching](https://binance-connector.readthedocs.io/en/stable/search.html?q=new_order&check_keywords=yes&area=default) leads to [this](https://binance-connector.readthedocs.io/en/stable/binance.spot.trade.html) page, which is only way to access docs for order methods.

**Comment by 2pd** [comment]
The document is updated. 

https://binance-connector.readthedocs.io/en/latest/CHANGELOG.html

Thanks
