### ISSUE TITLE
savings_flexible_product_position() - optional 'asset' parameter considered mandatory

### ISSUE THREAD

**Issue by gilcn** [binance/binance-connector-python#146]
### Issue subject
The 'asset' parameter for savings_flexible_product_position() is **not** a mandatory parameter as per the binance API, still binance-connector yields a TypeError exception if it is omitted.

### Environment
* Version of binance-connector-python: v1.13.0
* Python version: v3.10.4
* Operating system: Arch Linux

**Comment by 2pd** [comment]
thanks, we will fix it in the next release.

**Comment by tantialex** [comment]
Resolved with #153
