### ISSUE TITLE
Market SPOT buy orders do not execute for small precision values on quoteOrderQty

### ISSUE THREAD

**Issue by tdevinda** [binance/binance-connector-python#148]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
When executing a market buy order for a spot trade, if the quote order quantity is very small, (numerically) python converts the numbers in the API call to be scientific notation.

e.g. 
``` 
{'symbol': 'XVGBTC', 'side': 'BUY', 'type': 'MARKET', 'quoteOrderQty': 8.329e-05}
```

### Expected behaviour
quoteOrderQuantity should not be a scientific notation. it should go out as decimals with (maybe a configurable precision)

``` 
{'symbol': 'XVGBTC', 'side': 'BUY', 'type': 'MARKET', 'quoteOrderQty':  0.00008329}
```

### Actual behaviour
Numbers get converted to scientific notation and trade is not executed. API responses with an error
```
(400, -1100, "Illegal characters found in parameter 'quoteOrderQty'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'...)
```

### Steps to reproduce
Execute a market order for a small value below 0.000001

### Environment
Any OS
Python 3.10
Binance connector verson 1.11.0

**Comment by 2pd** [comment]
the best way to pass the amount into method is giving a string number.

```python
key = ""
secret = ""

params = {
    "symbol": "BTCUSDT",
    "side": "BUY",
    "type": "MARKET",
    "quoteOrderQty": "0.00008329",
}

client = Client(key, secret, base_url="https://testnet.binance.vision")

try:
    response = client.new_order(**params)
    logging.info(response)
except ClientError as error:
    logging.error(
        "Found error. status: {}, error code: {}, error message: {}".format(
            error.status_code, error.error_code, error.error_message
        )
    )

```

**Comment by tdevinda** [comment]
The API spec indicates this is numerical. Which is why I did not try that. I will try and update.
