### ISSUE TITLE
Unexpected 500s from client.staking_product_position()

### ISSUE THREAD

**Issue by vincentportella** [binance/binance-connector-python#150]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Getting unexpected 500s from the `GET /sapi/v1/staking/position` endpoint.

### Expected behaviour
I expected it to return my staking positions for `Matic*90` as it does for `Matic*60`.

### Actual behaviour
The following behaviour is consistent across multiple days.

Request: `client.staking_product_position(product='STAKING', productId='Matic*90')`
Response: `binance.error.ServerError: (500, '{"code":-1000,"msg":"An unknown error occurred while processing the request."}')`

It works just fine when swapping out `Matic*90` for `Matic*60`.

### Steps to reproduce
```
import os
from binance.spot import Spot

client = Spot(key=os.environ['BINANCE_KEY'], secret=os.environ['BINANCE_SECRET'])
print(client.time())

print(client.staking_product_position(product='STAKING', productId='Matic*60'))
print(client.staking_product_position(product='STAKING', productId='Matic*90'))
```

### Environment
Connector v1.13.0
Python 3.6.8
macOS 10.15.6

**Comment by 2pd** [comment]
```python

from binance.spot import Spot as Client

key = ""
secret = ""

client = Client(key, secret)
response = client.staking_product_position(product='STAKING', productId='Matic*90')

print(response)
```

Please try again, I can't reproduce with the same code.

**Comment by vincentportella** [comment]
I've tried every single `productId` available for staking (as far as I know, I've found 310) and the only one I run into this issue with is `Matic*90`. I don't think this is an issue with this connector but with the API itself. This is consistently happening. I've also reached out to support and they can't reproduce either. I imagine there are internal logs on your side you can look at.

Fwiw I have 150 matic staked through it on my account, which matches the total personal quota 🤷 . Though I also have the same situation with `Bnb*120` (0.5 BNB staked) and the api endpoint works fine for that.

Code used to test:

```
import os
from binance.spot import Spot

client = Spot(key=os.environ['BINANCE_KEY'], secret=os.environ['BINANCE_SECRET'])
print(client.time())

def try_staking_product_position(productId):
    try:
        client.staking_product_position(product='STAKING', productId=productId)
        print(productId + ' worked')
    except:
        print(productId + ' failed')

try_staking_product_position('Neo*15')
try_staking_product_position('Neo*30')
...
# I ran this for every single productId I've found
```

**Comment by 2pd** [comment]
I tried with another account with has staking of `Matic*90`, and there is no issue to get them from API.

**Comment by vincentportella** [comment]
I've re-implemented this in Go to ensure it wasn't the connector and I'm seeing the exact same behavior. `Matic*60` it works fine, `Matic*90` same error linked above. I understand that you're not able to reproduce this yourself, are you (or someone else) able to take a look at your internal api logs to corroborate what I am seeing?

Back to the Python connector, I've tried `client.staking_product_position(product='STAKING', asset='MATIC')` and I also get the error. When swapping out `MATIC` for `BNB` it works fine so I suspect it's because it's attempting to get the `Matic*90` position as well.

Also as part of re-implementing it I've found that the example response shown for https://binance-docs.github.io/apidocs/spot/en/#get-staking-product-position-user_data looks inaccurate. It is including a lot extra attributes which I'm not seeing in the api response (e.g. `extraRewardAPY`). Maybe it's due to only getting a subset of all possible product positions. It would be good to clear that up. I'd raise an issue for this but it doesn't seem that I can for https://github.com/binance/binance-spot-api-docs. The tab isn't there.

**Comment by 2pd** [comment]
> I've re-implemented this in Go to ensure it wasn't the connector and I'm seeing the exact same behavior. `Matic*60` it works fine, `Matic*90` same error linked above. I understand that you're not able to reproduce this yourself, are you (or someone else) able to take a look at your internal api logs to corroborate what I am seeing?
> 
> Back to the Python connector, I've tried `client.staking_product_position(product='STAKING', asset='MATIC')` and I also get the error. When swapping out `MATIC` for `BNB` it works fine so I suspect it's because it's attempting to get the `Matic*90` position as well.
> 
> Also as part of re-implementing it I've found that the example response shown for https://binance-docs.github.io/apidocs/spot/en/#get-staking-product-position-user_data looks inaccurate. It is including a lot extra attributes which I'm not seeing in the api response (e.g. `extraRewardAPY`). Maybe it's due to only getting a subset of all possible product positions. It would be good to clear that up. I'd raise an issue for this but it doesn't seem that I can for https://github.com/binance/binance-spot-api-docs. The tab isn't there.

- As I said I don't have issue to get `Matic*90`,  it could be a rare case that related to your account. You may contact customer support by providing more details, e.g. request log, error detail, account info, so they can help.
- In the document, some of the fields, e.g. `extraRewardAsset`, are only availalbe for project that has extra rewards.  If your staking position doesn't has those value, then it will not show.
- A better place to report API related question is dev.binance.vision.


Thanks
