### ISSUE TITLE
Add start and end time

### ISSUE THREAD

**Issue by forhad06** [binance/binance-connector-python#151]
Hey
I would like to add start and end time. I have tried this way but it's not working. Could you please give me a suggestion

`print(client.klines("BTCUSDT", "1h", limit=1000, startTime=1651977515, endTime=1654655915))`

Thanks in advance

**Comment by chairz** [comment]
Please state why is it not working by posting the error messages shown. It works fine on my end.

**Comment by forhad06** [comment]
Good Mornig Chairz,
I'm sorry, Simply there is no error showing, But just not getting data. Just getting a blank CSV file. but without end time or without time it's fine.

```
from binance.spot import Spot
import pandas as pd

client = Spot()
# Get last 10 klines of BNBUSDT at 1h interval
data1 = client.klines("BTCUSDT", "1m", limit=1000, startTime=1651977515, endTime=1654655915)

ds1 = pd.DataFrame(data1)
ds1.to_csv('1m.csv')

```

**Comment by tantialex** [comment]
The timestamps you provided are in seconds. The endpoint expected timestamps in milliseconds.
```
data1 = client.klines("BTCUSDT", "1m", limit=1000, startTime=1651977515000, endTime=1654655915000)
```

**Comment by forhad06** [comment]
My dear @tantialex 
Wonderful It's working fine 
Tanks champ! :D
