### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by hsh0107** [binance/binance-connector-python#152]
params = {
        "symbol": "SHIBUSDT",
        "side": "BUY",
        "type": "LIMIT",
        "timeInForce": "GTC",
        "quantity": 1003019,
        "price": "0.00000996"
    }

一直报错

(400, -1013, 'Filter failure: MIN_NOTIONAL'

**Comment by 2pd** [comment]
每单需要满足MIN_NOTIONAL的要求，应该是$10吧，你把数量加多点试试。

**Comment by hsh0107** [comment]
哦嚯， 果然不错， 大佬所言极是

**Comment by hsh0107** [comment]
> 每单需要满足MIN_NOTIONAL的要求，应该是$10吧，你把数量加多点试试。

喔嚯，大佬所言极是
