### ISSUE TITLE
Error: -2015, 'Invalid API-key, IP, or permissions for action.'

### ISSUE THREAD

**Issue by varunpan** [binance/binance-connector-python#155]
### Issue subject
I created a API Key and Secret using the guide provided just today. When using the the binance-connector, I keep getting an error that the API Key is invalid when trying to get any type of USER_DATA. 

### Expected behaviour
Print my account information

### Actual behaviour
binance.error.ClientError: (401, -2015, 'Invalid API-key, IP, or permissions for action.'

### Steps to reproduce
```
from binance.spot import Spot as Client
client = Client(key=BINANCE_API_KEY, secret=BINANCE_API_SECRET)
print(client.account())
```

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python - 1.13.0
* Python version - 3.9
* Operating system - OS X

**Comment by chairz** [comment]
It works fine on my end. 

1. Check that your api key & secret key are valid using postman.
2. Recreate the api key and test again.

**Comment by tantialex** [comment]
`binance.spot.Spot`'s default base url is `https://api.binance.com`. To make use of the US exchange, provide the base url in the constructor.

```python
Client(key=BINANCE_API_KEY, secret=BINANCE_API_SECRET, base_url='https://api.binance.us/')
```

Note: The US exchange does not support all endpoints.
