### ISSUE TITLE
Spot client new_order throws error with MIN_NOTIONAL

### ISSUE THREAD

**Issue by AniSkywalker** [binance/binance-connector-python#161]
### Issue subject
When a new_order is placed with quantity (not with quoteOrderQty), it is throwing ClientError with 'Filter failure: MIN_NOTIONAL'

### Expected behaviour
It should not check MIN_NOTIONAL unless quoteOrderQty is specified.

### Actual behaviour
It is failing due to MIN_NOTIONAL.
binance.error.ClientError: (400, -1013, 'Filter failure: MIN_NOTIONAL', 

### Steps to reproduce
spot_client = Spot(apikey, apisec)
spot_client.new_order(
            symbol=symbol,
            side=side,
            type="MARKET",
            quantity=str(0.006),
        )

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python 1.15.0
* Python version 3.7
* MAC

**Comment by 2pd** [comment]
what is the symbol?

**Comment by 2pd** [comment]
MIN_NOTIONAL error is not a library issue.  The notional value of the order is below the requirement, check `MIN_NOTIONAL` in the API document for more details.
