### ISSUE TITLE
install fails for python 3.10.5: requestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!

### ISSUE THREAD

**Issue by 369Martin369** [binance/binance-connector-python#167]
### Issue subject
Installation routine within python 3.10.5 (running in anaconda spyder) does success, but fails to execute because of dependecies urlib or charset

### Actual behaviour
---------------------------------------------------------------------------log-------------------------------------------------------
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:30:19) [MSC v.1929 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.33.0 -- An enhanced Interactive Python.

pip install binance-connector
Requirement already satisfied: binance-connector in c:\programdata\anaconda3\envs\py10\lib\site-packages (1.17.0)
Requirement already satisfied: pyOpenSSL>=19.0.0 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from binance-connector) (22.0.0)
Requirement already satisfied: service-identity>=21.1.0 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from binance-connector) (21.1.0)
Requirement already satisfied: autobahn>=21.2.1 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from binance-connector) (22.7.1)
Requirement already satisfied: Twisted>=21.2.0 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from binance-connector) (22.8.0)
Requirement already satisfied: requests>=2.25.1 in c:\users\marti\appdata\roaming\python\python310\site-packages (from binance-connector) (2.27.1)
Requirement already satisfied: hyperlink>=21.0.0 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from autobahn>=21.2.1->binance-connector) (21.0.0)
Requirement already satisfied: cryptography>=3.4.6 in c:\users\marti\appdata\roaming\python\python310\site-packages (from autobahn>=21.2.1->binance-connector) (36.0.2)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\envs\py10\lib\site-packages (from autobahn>=21.2.1->binance-connector) (65.3.0)
Requirement already satisfied: txaio>=21.2.1 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from autobahn>=21.2.1->binance-connector) (22.2.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\marti\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->binance-connector) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marti\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->binance-connector) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\marti\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->binance-connector) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\marti\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->binance-connector) (1.26.9)
Requirement already satisfied: attrs>=19.1.0 in c:\users\marti\appdata\roaming\python\python310\site-packages (from service-identity>=21.1.0->binance-connector) (21.4.0)
Requirement already satisfied: pyasn1 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from service-identity>=21.1.0->binance-connector) (0.4.8)
Requirement already satisfied: pyasn1-modules in c:\programdata\anaconda3\envs\py10\lib\site-packages (from service-identity>=21.1.0->binance-connector) (0.2.8)
Requirement already satisfied: six in c:\users\marti\appdata\roaming\python\python310\site-packages (from service-identity>=21.1.0->binance-connector) (1.16.0)
Requirement already satisfied: incremental>=21.3.0 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from Twisted>=21.2.0->binance-connector) (21.3.0)
Requirement already satisfied: twisted-iocpsupport<2,>=1.0.2 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from Twisted>=21.2.0->binance-connector) (1.0.2)
Requirement already satisfied: Automat>=0.8.0 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from Twisted>=21.2.0->binance-connector) (20.2.0)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from Twisted>=21.2.0->binance-connector) (4.3.0)
Requirement already satisfied: constantly>=15.1 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from Twisted>=21.2.0->binance-connector) (15.1.0)
Requirement already satisfied: zope.interface>=4.4.2 in c:\programdata\anaconda3\envs\py10\lib\site-packages (from Twisted>=21.2.0->binance-connector) (5.4.0)
Requirement already satisfied: cffi>=1.12 in c:\users\marti\appdata\roaming\python\python310\site-packages (from cryptography>=3.4.6->autobahn>=21.2.1->binance-connector) (1.15.0)
Requirement already satisfied: pycparser in c:\users\marti\appdata\roaming\python\python310\site-packages (from cffi>=1.12->cryptography>=3.4.6->autobahn>=21.2.1->binance-connector) (2.21)
Note: you may need to restart the kernel to use updated packages.

runfile('C:/DATA/MEGA/Info@Compensation.Network/python/Binance Market EMA Prozent Margin/main9.py', wdir='C:/DATA/MEGA/Info@Compensation.Network/python/Binance Market EMA Prozent Margin')
C:\Users\Marti\AppData\Roaming\Python\Python310\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\py10\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\data\mega\info@compensation.network\python\binance market ema prozent margin\main9.py", line 6, in <module>
    from binance.client  import Client  #importing client

ModuleNotFoundError: No module named 'binance.client'
------------------------------------------------log---------------------------------------------------------------------------------------

### Steps to reproduce
pip install binance-connector

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python (latest github)
* Python version 3.10.6
* Operating system (Win10, Anaconda,

**Comment by 2pd** [comment]
can you run 

```
pip list | grep requests
pip list | grep urllib3
```

and show us the result

**Comment by 369Martin369** [comment]
man, you fooled a windows guy with your "| " addon....

But figured it out alone :-). here you are: 

pip list grep requests
Package                       Version
----------------------------- -----------
aiodns                        3.0.0
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
APScheduler                   3.6.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.12.9
asttokens                     2.0.8
async-timeout                 4.0.2
atomicwrites                  1.4.1
attrs                         21.4.0
autobahn                      22.7.1
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.10.3
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bcrypt                        3.2.2
beautifulsoup4                4.11.1
binance                       0.3
binance-connector             1.17.0
binance-connector-python      0.6.0
binaryornot                   0.4.4
black                         22.6.0
bleach                        5.0.1
brotlipy                      0.7.0
ccxt                          1.78.3
certifi                       2021.10.8
cffi                          1.15.0
chardet                       5.0.0
charset-normalizer            2.0.12
click                         8.1.3
cloudpickle                   2.2.0
colorama                      0.4.5
constantly                    15.1.0
cookiecutter                  2.1.1
cryptography                  36.0.2
debugpy                       1.3.0
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.5.1
dnspython                     2.2.1
docutils                      0.19
entrypoints                   0.4
et-xmlfile                    1.1.0
eventlet                      0.33.0
executing                     1.0.0
fastjsonschema                2.16.1
flake8                        4.0.1
flit_core                     3.7.1
frozenlist                    1.3.0
greenlet                      1.1.2
hyperlink                     21.0.0
idna                          3.3
imagesize                     1.4.1
importlib-metadata            4.11.4
importlib-resources           5.9.0
incremental                   21.3.0
inflection                    0.5.1
intervaltree                  3.0.2
ipykernel                     6.15.2
ipython                       7.33.0
ipython-genutils              0.2.0
isort                         5.10.1
jaraco.classes                3.2.2
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.16.0
jupyter_client                7.3.5
jupyter_core                  4.11.1
jupyterlab-pygments           0.2.2
keyring                       23.9.1
lazy-object-proxy             1.7.1
lxml                          4.9.1
MarkupSafe                    2.1.1
matplotlib-inline             0.1.6
mccabe                        0.6.1
mistune                       2.0.4
more-itertools                8.14.0
multidict                     6.0.2
mypy-extensions               0.4.3
nbclient                      0.6.8
nbconvert                     7.0.0
nbformat                      5.4.0
nest-asyncio                  1.5.5
notebook                      6.4.12
numpy                         1.23.3
numpydoc                      1.4.0
openpyxl                      3.0.9
packaging                     21.3
pandocfilters                 1.5.0
paramiko                      2.11.0
parso                         0.8.3
pathspec                      0.10.1
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.2.2
pkgutil_resolve_name          1.3.10
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.31
psutil                        5.9.2
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycares                       4.1.2
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.13.0
pylint                        2.15.2
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.1
PySide2                       5.15.2.1
PySocks                       1.7.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                6.1.2
python-telegram-bot           13.4.1
Pythonic                      1.11
pytoolconfig                  1.2.2
pytz                          2022.1
pytz-deprecation-shim         0.1.0.post0
pywin32                       303
pywin32-ctypes                0.2.0
pywinpty                      2.0.7
PyYAML                        6.0
pyzmq                         23.2.1
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.1.1
qtconsole                     5.3.2
QtPy                          2.2.0
requests                      2.27.1
rope                          1.3.0
Rtree                         1.0.0
Send2Trash                    1.8.0
service-identity              21.1.0
setuptools                    65.3.0
shiboken2                     5.15.2.1
sip                           6.6.2
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.1.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
stack-data                    0.5.0
TA-Lib                        0.4.19
terminado                     0.15.0
text-unidecode                1.3
textdistance                  4.4.0
three-merge                   0.1.1
tinycss2                      1.1.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.4
tornado                       6.1
traitlets                     5.3.0
Twisted                       22.8.0
twisted-iocpsupport           1.0.2
txaio                         22.2.1
typing_extensions             4.3.0
tzdata                        2022.1
tzlocal                       4.2
ujson                         5.4.0
Unidecode                     1.3.4
urllib3                       1.26.9
watchdog                      2.1.9
wcwidth                       0.2.5
webencodings                  0.5.1
whatthepatch                  1.0.2
wheel                         0.37.1
win-inet-pton                 1.1.0
wrapt                         1.14.1
yapf                          0.32.0
yarl                          1.7.2
zipp                          3.8.1
zope.interface                5.4.0
Note: you may need to restart the kernel to use updated packages.

pip list grep urllib3
Package                       Version
----------------------------- -----------
aiodns                        3.0.0
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
APScheduler                   3.6.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.12.9
asttokens                     2.0.8
async-timeout                 4.0.2
atomicwrites                  1.4.1
attrs                         21.4.0
autobahn                      22.7.1
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.10.3
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bcrypt                        3.2.2
beautifulsoup4                4.11.1
binance                       0.3
binance-connector             1.17.0
binance-connector-python      0.6.0
binaryornot                   0.4.4
black                         22.6.0
bleach                        5.0.1
brotlipy                      0.7.0
ccxt                          1.78.3
certifi                       2021.10.8
cffi                          1.15.0
chardet                       5.0.0
charset-normalizer            2.0.12
click                         8.1.3
cloudpickle                   2.2.0
colorama                      0.4.5
constantly                    15.1.0
cookiecutter                  2.1.1
cryptography                  36.0.2
debugpy                       1.3.0
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.5.1
dnspython                     2.2.1
docutils                      0.19
entrypoints                   0.4
et-xmlfile                    1.1.0
eventlet                      0.33.0
executing                     1.0.0
fastjsonschema                2.16.1
flake8                        4.0.1
flit_core                     3.7.1
frozenlist                    1.3.0
greenlet                      1.1.2
hyperlink                     21.0.0
idna                          3.3
imagesize                     1.4.1
importlib-metadata            4.11.4
importlib-resources           5.9.0
incremental                   21.3.0
inflection                    0.5.1
intervaltree                  3.0.2
ipykernel                     6.15.2
ipython                       7.33.0
ipython-genutils              0.2.0
isort                         5.10.1
jaraco.classes                3.2.2
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.16.0
jupyter_client                7.3.5
jupyter_core                  4.11.1
jupyterlab-pygments           0.2.2
keyring                       23.9.1
lazy-object-proxy             1.7.1
lxml                          4.9.1
MarkupSafe                    2.1.1
matplotlib-inline             0.1.6
mccabe                        0.6.1
mistune                       2.0.4
more-itertools                8.14.0
multidict                     6.0.2
mypy-extensions               0.4.3
nbclient                      0.6.8
nbconvert                     7.0.0
nbformat                      5.4.0
nest-asyncio                  1.5.5
notebook                      6.4.12
numpy                         1.23.3
numpydoc                      1.4.0
openpyxl                      3.0.9
packaging                     21.3
pandocfilters                 1.5.0
paramiko                      2.11.0
parso                         0.8.3
pathspec                      0.10.1
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.2.2
pkgutil_resolve_name          1.3.10
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.31
psutil                        5.9.2
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycares                       4.1.2
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.13.0
pylint                        2.15.2
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.1
PySide2                       5.15.2.1
PySocks                       1.7.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                6.1.2
python-telegram-bot           13.4.1
Pythonic                      1.11
pytoolconfig                  1.2.2
pytz                          2022.1
pytz-deprecation-shim         0.1.0.post0
pywin32                       303
pywin32-ctypes                0.2.0
pywinpty                      2.0.7
PyYAML                        6.0
pyzmq                         23.2.1
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.1.1
qtconsole                     5.3.2
QtPy                          2.2.0
requests                      2.27.1
rope                          1.3.0
Rtree                         1.0.0
Send2Trash                    1.8.0
service-identity              21.1.0
setuptools                    65.3.0
shiboken2                     5.15.2.1
sip                           6.6.2
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.1.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
stack-data                    0.5.0
TA-Lib                        0.4.19
terminado                     0.15.0
text-unidecode                1.3
textdistance                  4.4.0
three-merge                   0.1.1
tinycss2                      1.1.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.4
tornado                       6.1
traitlets                     5.3.0
Twisted                       22.8.0
twisted-iocpsupport           1.0.2
txaio                         22.2.1
typing_extensions             4.3.0
tzdata                        2022.1
tzlocal                       4.2
ujson                         5.4.0
Unidecode                     1.3.4
urllib3                       1.26.9
watchdog                      2.1.9
wcwidth                       0.2.5
webencodings                  0.5.1
whatthepatch                  1.0.2
wheel                         0.37.1
win-inet-pton                 1.1.0
wrapt                         1.14.1
yapf                          0.32.0
yarl                          1.7.2
zipp                          3.8.1
zope.interface                5.4.0
Note: you may need to restart the kernel to use updated packages.

**Comment by 2pd** [comment]
I think it's the versions conflicts of your requests, urllib3 or other packages.
Please feel free to setup a new virtual python env and install the package.
