### ISSUE TITLE
Websocket connection was closed uncleanly

### ISSUE THREAD

**Issue by aksharavalsalakumar** [binance/binance-connector-python#169]
### Issue subject
Websocket connection was closed uncleanly (1006) and twisted.internet.error

### Expected behaviour
subscribe and get trade updates for all available symbols using "trade" API .

### Actual behaviour
I used Binance python connector API and tried to get trade updates for all available symbols using trade api .But i keep getting twisted internet errors and 1006 errors frequently.

### Steps to reproduce

```python
my_client = SpClient()
my_client.start()
spot_client = Client(base_url="https://api.binance.com")
response = spot_client.exchange_info()["symbols"]
markets_df = pd.DataFrame(response)
markets_df_filtrd = markets_df[markets_df["status"] == 'TRADING']
tickers_bi = list(markets_df_filtrd['symbol'].values)
for i, ticker in enumerate(tickers_bi):
        my_client.trade(symbol=ticker, interval="1m", id=1, callback=callback)

def callback():
    print('--callback')

```
### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python -v1.0.16
* python -3.9.7
* 0s -linux

**Comment by 2pd** [comment]
1. Please upgrade the library to the latest version
2. which line throws the error?  I'm not sure what is the `SpClient`

**Comment by aksharavalsalakumar** [comment]
SpClient is 
 from binance.websocket.spot.websocket_client import SpotWebsocketClient as SpClient


I have upgraded the library to the latest version and checked.still I am facing the same issue

**Comment by 2pd** [comment]
From the code above, you are subscribe to trade streams of all TRADING symbols, that is over 1000 streams that you are handling. That's a lot of data, the client may not able to process the data in socket in time, the server can drop the inefficient clients in connection.  You could reduce the connections amount, and see if that helps.
