### ISSUE TITLE
Error handling for #104, #107

### ISSUE THREAD

**Issue by EzDani1** [binance/binance-connector-python#170]
hello I'm 15 years old and I need your help please
my binance-connector bot runs for hours and....sporadically it aborts

These are the 2 errors I suffer:

requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

I have to re-start the program manually.
Please be so kind and suggest me how to handle such errors, so that the program restarts automatically

Thanks a lot for your help
I was not able to find fixes anywhere else...

**Comment by ANTOGUTAR** [comment]
He visto que pides ayuda para ... (no lo he visto). Inicialmente y no
censurando tu valor y atrevimiento de trabajar con PALABRAS MAYORES.
Yo he intentando conseguir alguna ayuda a través de los trades y en varias
ocasiones he conseguido ganar, pero no he conseguido cobrar.
Es un "JUEGO" muy peligrosos, si tienes VALOR (que lo has demostrado) y
mucha confianza en.  "TI'"  seguro que conseguirás lo que quieras. Todos
tenemos ese poder.
Hay muchas gente que: es muy caro, no podemos, no ...
Si tu te lo preparas, con cabeza, pidiendo consejo pero no fíarte de nadie.
TIENES EL PODER, ; "TU"

TE ADJUNTO Unos Padres Nuestros

**Comment by 2pd** [comment]
Thanks for your feedback, we are happy to give info that may help your debug.

Can you find out the stack error info that should be able to find from your log file, it will help us to understand which method throw this error.

Thanks
