### ISSUE TITLE
Testnet cancelled order status is CANCELED not CANCELLED

### ISSUE THREAD

**Issue by esonbest** [binance/binance-connector-python#171]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
when we call client.get_order() 
[api in testnet]
in the  feed back message of cancelled order, the status is CANCELED not CANCELLED
may be there is a type error.
can you check it ,thanks.
{'symbol': 'ETHBUSD', 'orderId': 5136673, 'orderListId': -1, 'clientOrderId': 'ajMiuPTqQZboizu6R3Bm2Y', 'price': '2000.00000000', 'origQty': '2.00000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': '**CANCELED**', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'SELL', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1663820173860, 'updateTime': 1663824297819, 'isWorking': True, 'origQuoteOrderQty': '0.00000000'}

**Comment by esonbest** [comment]
it seems the right format is CANCELED not CANCELLED.

**Comment by 2pd** [comment]
@esonbest  The status of an order that has been canceled is `CANCELED`. Did you see anywhere that says it's `CANCELLED`
