### ISSUE TITLE
Binance Spot - How to get average price of multiple market orders

### ISSUE THREAD

**Issue by Charlespe19** [binance/binance-connector-python#175]
### Issue subject
I am working with python 'binance connector' in the SPOT market. After making some market buy orders, I need to get the average price of those orders, I have been locking for "how to get this information directly from binance API (not calculating by myself)".
Im using the testnet now: 

`response = self.client.new_order(symbol=self.exchange, side=side_operation, type='MARKET', quantity=self.amount)`

After 2 buy market, the response return the following:

```
{'symbol': 'BTCUSDT', 'orderId': 518770, 'orderListId': -1, 'clientOrderId': 'WbFPLGqjFpDBKFjrYP719A',
 'transactTime': 1665073924856, 'price': '0.00000000', 'origQty': '0.03930000', 'executedQty': '0.03930000',
 'cummulativeQuoteQty': '787.84670700', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY',
 'fills': [{'price': '20046.99000000', 'qty': '0.03930000', 'commission': '0.00000000', 'commissionAsset': 'BTC',
            'tradeId': 235957}]}
```

### Expected behaviour
I was thinking that the ['fills']['price'] after 2 or more buys, it was the average price of those 2 buys but no, that's the price market which the last buy market was done.

In another "issue" I read that dividing the `'cummulativeQuoteQty': '787.84670700'` by `'executedQty': '0.03930000'` i can obtain the average of the orders, but after divide, I obtain the entry price of the current market order which was `'price': '20046.99000000'`.

### Actual behaviour
in the `'fills' 'price': '20046.99000000'` is the price market which the last buy market was done not the average price (after multiple orders).

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python:  1.18.0
* Python version: 3.10.4

### Question
Is there a way to get the average price of multiple market orders done? (not calculating by myself but directly from binance).
Thank you in advance for your support.

**Comment by 2pd** [comment]
the data in `fills` is each trades that filling your order with opposite side. As it's a `MARKET` order, the price in each trades can be different depends on the current market.

```shell
cummulativeQuoteQty / executedQty = avgPrice of the order
```
