### ISSUE TITLE
Binance Spot - Random orders count in client.get_orders

### ISSUE THREAD

**Issue by recycletechno** [binance/binance-connector-python#176]
### Issue subject
Today morning I found that I get different API answers from client.get_orders on my account. For example LUNCUSDT symbol.

### Expected behaviour
When I run this example from github (https://github.com/binance/binance-connector-python/blob/master/examples/spot/trade/get_orders.py) I should get 21 entries. I changed only API keys and symbol = LUNCUSDT

In real I have 21 entries for LUNCUSDT 

### Actual behaviour
When I run this example I get sometimes 18 and sometimes 21 entries. I can run script for example 10 times per minute and get 5 times 18, 5 times 21 entries. It works like random.

### Steps to reproduce
`import logging
from binance.spot import Spot as Client
from binance.lib.utils import config_logging
from binance.error import ClientError

config_logging(logging, logging.DEBUG)

key = "mykey"
secret = "mysecret"

client = Client(key, secret)

try:
    response = client.get_orders("LUNCUSDT")
    logging.info(response)
except ClientError as error:
    logging.error(
        "Found error. status: {}, error code: {}, error message: {}".format(
            error.status_code, error.error_code, error.error_message
        )
    )`

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python 1.18.0
* Python version 3.9
* Operating system (tried on Ubuntu and Windows 10)

**Comment by 2pd** [comment]
It's a concern from the API side, not directly related to this library. Let's discuss in this topic.
https://dev.binance.vision/t/api-v3-allorders-returns-random-results/13160
