### ISSUE TITLE
binance.error.ClientError: 400, -1121

### ISSUE THREAD

**Issue by ThiagoZarur** [binance/binance-connector-python#181]
Binance error of the client 400, -1121 'Invalid symbol'

### Expected behaviour
I want to active a new order in binance futures

![image](https://user-images.githubusercontent.com/88751496/200742905-3b9ebee2-ed76-45b3-b2f9-f096258a08f0.png)

**Comment by jonte-z** [comment]
Hi,

Are you using the testnet base_url by any chance? You will get an `Invalid Symbol` error if you're using testnet since ALPHAUSDT pair doesn't exist on the testnet. 

Cheers,
