### ISSUE TITLE
cancel orders doesn't work

### ISSUE THREAD

**Issue by arisAlexis** [binance/binance-connector-python#185]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
cancel orders doesn't work

### Expected behaviour
cancel orders 

### Actual behaviour
    raise ClientError(status_code, err["code"], err["msg"], response.headers)
binance.error.ClientError: (400, -2011, 'Unknown order sent.', {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '42', 'Connection': 'keep-alive', 'Date': 'Thu, 24 Nov 2022 11:33:20 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'lalala', 'x-mbx-used-weight': '1', 'x-mbx-used-weight-1m': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 b26a5eb677aed7368a2c7fd7f1d673dc.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS1-P1', 'X-Amz-Cf-Id': 'lalala'})

### Steps to reproduce
client.cancel_open_orders(symbol='BTCUSDT')

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python 1.18.0
* Python 3.1
* Operating system Windows 11

**Comment by jonte-z** [comment]
Please make sure that you actually have open orders for the symbol you're sending with the `cancel_open_orders` request. You will get that error if you don't currently have any open orders for the symbol.
