### ISSUE TITLE
(Unannounced) Binance read-only public API endpoints are no longer available in the US / restricted locations 

### ISSUE THREAD

**Issue by gldstrrbt** [binance/binance-connector-python#190]
Up until today, the Binance public read-only data API has been available for all to use and access. But now, any device not connected to a VPN / proxy server outside of restricted areas is getting 451 errors.

The customer service rep I spoke with assured me that they (Binance) put in their "best efforts" to notify those who would be affected by this cut off of their read-only data endpoints... by email. Email? Really? They're surely aware that many devs from all over the world (restricted and non-restricted alike) make use of the read-only API endpoints that they've provided up until today. They're also likely aware that many folks have products (charting/analytics/etc) which rely on this read-only data they provide, considering they're one of, if not THE, top exchange(s) in the world, meaning their data paints a better picture of global trading activity.

Binance should have been responsible and should have given all devs a heads up through a public announcement, stating how they're cutting off their access to their read-only data in "restricted" locations, such as the US. It makes zero sense why they would pull this, especially considering that this read-only data is still accessible for all to read around the world through the tables and advanced charts provided on their core website... just not through their public API.

The customer service rep insisted that I use the Binance US API, but again, the previously publicly available read-only data provided by the main Binance is much more robust and paints a clearer picture of international trading activity, and doesn't limit devs to data from one region. They also insisted that I create a ticket speaking to this, knowing that it would require me to create a Binance account... which I'm restricted from doing.

So after being fed up with all the corporate speak, mental gymnastics, and gaslighting the rep pulled, I decided to write here in hopes of letting those using the API in the US and other now restricted areas, know that their access to the core read-only Binance public API has been cutoff as of today. Also wrote this in hopes of catching any of the Binance dev's attention and maybe reversing this cutoff or at least encourage their team to reverse the decision should they have any actual in this.

Yes, a proxy server / VPN can be connected to in a non-restricted area to side step this, but for those (such as myself) in situations where their project or product is purely client side, this is negatively affecting my livelihood/progression of my business/offerings.

**Comment by 2pd** [comment]
Please check the API document, I think there is base url for public data only.
Also this is not related to this library.
