### ISSUE TITLE
reference conflict

### ISSUE THREAD

**Issue by ead353** [binance/binance-connector-python#192]
Please tell me, among the SDKs given by Binance, the spot SDK and one of the perpetual contract SDKs are both referenced from binance. Will this conflict? How to deal with it.

from binance.spot import Spot <——> from binance.cm_futures import CMFutures

**Comment by Adnan4733** [comment]
Yes afcors

**Comment by jonte-z** [comment]
If you have both `binance-connector` and `binance-futures-connector` installed, they can both function properly even when called in the same file. 

For example, test the following code that imports CM_Futures from `binance.cm_futures` and Spot from `binance.spot`:

```python
from binance.spot import Spot
from binance.cm_futures import CMFutures

spot_client = Spot()
futures_client = CMFutures()

print("Spot:")
print(spot_client.agg_trades("BTCUSDT", limit=10))
print("\n")
print("CM Futures:")
print(futures_client.agg_trades("BTCUSD_PERP", limit=10))
```

**Comment by RobinDeBaets** [comment]
This is incorrect. 

https://github.com/binance/binance-futures-connector-python/blob/e09bb462d0e310b7a4f4a80c7d4e2b77c21817ba/binance/api.py#L77

https://github.com/binance/binance-connector-python/blob/cfa1620a6837b38f001d73f72d345434ec1205c2/binance/api.py#L78

These functions have different signatures, so if you didn't install the two packages in the correct order, you'll run into issues.
Absolute joke that these packages share the same namespace.
