### ISSUE TITLE
twisted-iocpsupport error while importing binance-connector

### ISSUE THREAD

**Issue by duruburak** [binance/binance-connector-python#197]
Hi I get this traceback when I try to `pip install binance-connector`. Any ideas to solve it?

```python
Building wheels for collected packages: twisted-iocpsupport
  Building wheel for twisted-iocpsupport (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for twisted-iocpsupport (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'twisted_iocpsupport.iocpsupport' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for twisted-iocpsupport
Failed to build twisted-iocpsupport
ERROR: Could not build wheels for twisted-iocpsupport, which is required to install pyproject.toml-based projects
```

**Comment by jonte-z** [comment]
Hi there,

From looking at the log you posted it states `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

Try doing as it says by downloading Microsoft C++ Build tools from https://visualstudio.microsoft.com/visual-cpp-build-tools/ and try the `pip install` again.

**Comment by duruburak** [comment]
> Hi there,
> 
> From looking at the log you posted it states `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`
> 
> Try doing as it says by downloading Microsoft C++ Build tools from https://visualstudio.microsoft.com/visual-cpp-build-tools/ and try the `pip install` again.

Yes I saw it too but I didn't know which one to install, do you know which one?

![visual c](https://user-images.githubusercontent.com/100048974/210287094-518cd52d-5930-46ff-a8a9-9162c4c0311c.png)

**Comment by jonte-z** [comment]
> Yes I saw it too but I didn't know which one to install, do you know which one?

The one from the error output that I linked in my previous reply that takes you to a page with a button saying "Download Build Tools". Download that and install it then try the `pip install` again.
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by duruburak** [comment]
> > Yes I saw it too but I didn't know which one to install, do you know which one?
> 
> The one from the error output that I linked in my previous reply that takes you to a page with a button saying "Download Build Tools". Download that and install it then try the `pip install` again. https://visualstudio.microsoft.com/visual-cpp-build-tools/

Yes, the image is from visual studio build tools.
