### ISSUE TITLE
asset_info = Binance_client.user_asset(asset=token) gives me an error

### ISSUE THREAD

**Issue by hammerjoe** [binance/binance-connector-python#207]
Pycharm is warning me of an error for this line.
The error is Parameter 'self' unfilled

from binance.spot import Spot as Binance_client
Binance_client = Binance_client(api_key=api_key, api_secret=api_secret)

token = 'bat'
asset_info = Binance_client.user_asset(asset=token)

Why am I getting this error and how do I get rid of it?

**Comment by 2pd** [comment]
I can reproduce this issue.
- Have you installed the library `python-connector`?
- what's the version of it
- what's the version of your python
- can you try to run the example file directly from this repo?

**Comment by 2pd** [comment]
Oh i see the problem.

`Binance_client = Binance_client(api_key=api_key, api_secret=api_secret)` =>
`client = Binance_client(api_key=api_key, api_secret=api_secret)`

then 

`
asset_info = client.user_asset(asset=token)
`

so basically you can call the method from the class of `Binance_client`.

**Comment by hammerjoe** [comment]
I still get the same warning Parameter 'self' unfilled.
