### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by ZhangPeibin** [binance/binance-connector-python#208]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
在我的电脑都翻墙的情况下。并且在终端通过curl www.google.com 获取到内容的基础下，无法通过wscat 连接到 websocket api
但是在浏览器上面的websocket测试网站上面是可以连接到 wss://stream.binance.com:9443.

目前遇到的问题是
1：终端无法连接到  wss://stream.binance.com:9443.
2:   通过pycharm 写的python也无法使用该库连接到 wss://stream.binance.com:9443

mac的终端和 pycharm的终端都可以通过curl cip.cc 获取到ip在台湾

急求帮助！

### Environment
Provide any relevant information about your setup, such as:
* binance-connector-python :  3.0.0
* Python version ：3.9
* Operating system ： mac

**Comment by 2pd** [comment]
```shell

curl -v -o - --http1.1 \
--include \
--no-buffer \
--header "Connection: Upgrade" \
--header "Upgrade: websocket" \
--header "Host: stream.binance.com:9443" \
--header "Origin: https://stream.binance.com:9443" \
--header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
--header "Sec-WebSocket-Version: 13" \
https://stream.binance.com:9443/ws/bnbusdt@ticker


```

试试这个可以连上么？

**Comment by ZhangPeibin** [comment]
已解决。谢谢
