### ISSUE TITLE
Invalid leading whitespace

### ISSUE THREAD

**Issue by Leggerla** [binance/binance-connector-python#209]
### Issue subject
Usage example doesn't work (at least for spot test network)

### Expected behaviour
New order should be placed (on spot test network)

### Actual behaviour
_I replaced my path to the project with "..." for readability_

> Traceback (most recent call last):
> File "...\main.py", line 42, in start
>     response = client.new_order(**params)
>   File "...\venv\lib\site-packages\binance\spot\trade.py", line 68, in new_order
>     return self.sign_request("POST", url_path, params)
>   File "...\venv\lib\site-packages\binance\api.py", line 84, in sign_request
>     return self.send_request(http_method, url_path, payload)
>   File "...\venv\lib\site-packages\binance\api.py", line 117, in send_request
>     response = self._dispatch_request(http_method)(**params)
>   File "...\venv\lib\site-packages\requests\sessions.py", line 635, in post
>     return self.request("POST", url, data=data, json=json, **kwargs)
>   File "...\venv\lib\site-packages\requests\sessions.py", line 573, in request
>     prep = self.prepare_request(req)
>   File "...\venv\lib\site-packages\requests\sessions.py", line 484, in prepare_request
>     p.prepare(
>   File "...\venv\lib\site-packages\requests\models.py", line 369, in prepare
>     self.prepare_headers(headers)
>   File "...\venv\lib\site-packages\requests\models.py", line 491, in prepare_headers
>     check_header_validity(header)
>   File "...\venv\lib\site-packages\requests\utils.py", line 1043, in check_header_validity
>     _validate_header_part(value, "value", HEADER_VALIDATORS[type(value)][1])
>   File "...\venv\lib\site-packages\requests\utils.py", line 1048, in _validate_header_part
>     raise InvalidHeader(
> requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: '\nE3hb866sdGl11k78d3ZCyX0tAyXln27Jq2AOOyBEl974vBkpBOKqe9dR0qxu6ddx'
> 
> Process finished with exit code 1
> 

### Steps to reproduce
```
from binance.spot import Spot

api_key, api_secret = get_api_key()
client = Spot(api_key=api_key, api_secret=api_secret, base_url="https://testnet.binance.vision")

# Post a new order
params = {
    'symbol': 'BTCUSDT',
    'side': 'SELL',
    'type': 'LIMIT',
    'timeInForce': 'GTC',
    'quantity': 0.002,
    'price': 9500
}

response = client.new_order(**params)
print(response)

```

### Environment
* Version of binance-connector-python: 2.0.0
* Python version: 3.9
* Operating system: Windows

**Comment by 2pd** [comment]
I have a try on Mac, the code works fine for me, may try on Windows.

Are you able to get result on other method, like https://github.com/binance/binance-connector-python/blob/master/examples/spot/market/time.py

**Comment by Leggerla** [comment]
@2pd

Yep, time works absolutely fine. And even getting klines works fine. I've got trouble with `client.account()` and `client.new_order()`

**Comment by Leggerla** [comment]
Did the same on Mac, works for me as well. Weird.

**Comment by 2pd** [comment]
Did you install the correct package?

```shell
pip install binance-connector
```

**Comment by 2pd** [comment]
it looks fine for me to place order on Windows.

**Comment by Leggerla** [comment]
I think I installed the correct one, yeah:
![image](https://user-images.githubusercontent.com/52498629/220536664-32d5a3eb-5a7f-4adc-8c10-a54fa758564f.png)

Did you try it with the latest version?

**Comment by 2pd** [comment]
Please give it a try on the latest version v3.0.0rc1

**Comment by Leggerla** [comment]
I just tried it again, installing binance-connector in PyCharm, I guess the main version. And it worked fine.
