### ISSUE TITLE
Install binance-futures-connector-python and then install binance-connector-python file send override conflict

### ISSUE THREAD

**Issue by 1163849662** [binance/binance-connector-python#212]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.
Install binance-futures-connector-python and then install binance-connector-python file send override conflict

### Expected behaviour
Describe what should happen.
um_futures file is overwritten
![image](https://user-images.githubusercontent.com/64328109/220244192-ec31eb52-9ea1-4b12-ac15-3b8e4d0945df.png)
![image](https://user-images.githubusercontent.com/64328109/220244248-ba37beeb-431e-44c8-90f3-c3e31b293db9.png)
[binance-connector-python] and [binance-futures-connector-python] act on the binance folder at the same time
### Actual behaviour
Describe what happens instead. Please include the complete failure message.
Traceback (most recent call last):
  File "/Users/snieopq/PycharmProjects/flaskProject/Webhook/Futures/user_data.py", line 6, in <module>
    from binance.um_futures import UMFutures
ModuleNotFoundError: No module named 'binance.um_futures'

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.
import time
import logging
from binance.lib.utils import config_logging
from binance.um_futures import UMFutures
from binance.websocket.um_futures.websocket_client import UMFuturesWebsocketClient

![截屏2023-02-21 上午11 56 31](https://user-images.githubusercontent.com/64328109/220243934-bc5dbf65-db65-422e-ad00-9616938f9e9f.png)

**Comment by 2pd** [comment]
![image](https://user-images.githubusercontent.com/365354/220268398-9d842f08-6cf4-49a2-bd59-c3abbfcad700.png)

![image](https://user-images.githubusercontent.com/365354/220268476-7a7c547b-d950-45e0-80e1-3c07fe7bf877.png)


```python

import logging
from binance.spot import Spot
from binance.um_futures import UMFutures
from binance.lib.utils import config_logging

config_logging(logging, logging.DEBUG)

spot_client = Spot()
print(spot_client.time())

um_futures_client = UMFutures()
logging.info(um_futures_client.time())

```

**Comment by 2pd** [comment]
this works for me.

**Comment by aisling-2** [comment]
Hi @1163849662, since there's no new updates from you for a while since our last comment, we're closing this post for now. Please feel free to reopen if necessary.
