### ISSUE TITLE
Websocket api v3 sending messages at short intervals will be interrupted by server main activity

### ISSUE THREAD

**Issue by 1163849662** [binance/binance-connector-python#213]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
When the request does not reach the limit, the Websocket api v3 sends messages at short intervals and the server actively disconnects. It works fine when the time interval between sending requests is relatively large.
`[ {'rateLimitType': 'ORDERS', 'interval': 'SECOND', 'intervalNum': 10, ' limit': 50, 'count': 3}, {'rateLimitType': 'ORDERS', 'interval': 'DAY', 'intervalNum': 1, 'limit': 160000, 'count': 2124}, {' rateLimitType': 'REQUEST_WEIGHT', 'interval': 'MINUTE', 'intervalNum': 1, 'limit': 1200, 'count': 3}]`
### Expected behaviour
Server Websocket api disconnected

### Actual behaviour
2023-02-26 03:40:02.049 UTC WARNING binance_xh.websocket.websocket_client: CLOSE frame received, closing websocket connection

### simple example
`#!/usr/bin/env python

import logging
import time
from binance_xh.lib.utils import config_logging
from binance_xh.websocket.spot.websocket_api import SpotWebsocketAPIClient
from examples.utils.prepare_env import get_api_key

api_key, api_secret = get_api_key()

config_logging(logging, logging.DEBUG)

def on_close(_):
    logging.info("Do custom stuff when connection is closed")

def message_handler(_, message):
    print(message)

my_client = SpotWebsocketAPIClient(
    stream_url="wss://ws-api.binance.com/ws-api/v3",
    api_key=api_key,
    api_secret=api_secret,
    on_message=message_handler,
    on_close=on_close,
)

my_client.new_order(
    id=12345678,
    symbol="BTCAUD",
    side="BUY",
    type="LIMIT",
    timeInForce="GTC",
    quantity=0.0003,
    price=36123.62,
    newClientOrderId="my_order_id_1",
    newOrderRespType="RESULT",
)

time.sleep(2)

logging.info("closing ws connection")
my_client.stop()`

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python rc-3.0.0rc1
* Python3.11
* mac
![截屏2023-02-26 下午11 31 12](https://user-images.githubusercontent.com/64328109/221445432-80bac06c-b3b3-4aec-8499-f9b52e370c14.png)

**Comment by aisling-2** [comment]
Hello, the example doesn't cover your reported issue at the screenshot.
But I guess what you mean is Websocket API is automatically disconnected when it receives an error ( f/your screenshot `400`)?

**Comment by 2pd** [comment]
The example is designed to close the connection after 2 seconds. You can set to a longer period like 10000 seconds.

time.sleep(10000)
