### ISSUE TITLE
window 電腦下websocket 不能連接

### ISSUE THREAD

**Issue by power-jun** [binance/binance-connector-python#217]
WebSocket connection closed: connection was closed uncleanly ("SSL error: unregistered scheme (in )"), code: 1006, clean: False, reason: connection was closed uncleanly ("SSL error: unregistered scheme (in )")
Lost connection to Server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]. Retrying: 2

**Comment by aisling-2** [comment]
Hello, this error has been mentioned in the past. Please refer to https://github.com/binance/binance-connector-python/issues/57.
