### ISSUE TITLE
How to keep the user data Websocket stream alive?

### ISSUE THREAD

**Issue by qiqipipioioi** [binance/binance-connector-python#218]
A User Data Stream listenKey is valid for 60 minutes after creation. To prevent a timeout and keep it alive, it is recommended to send a ping about every 30 minutes.
Doing a PUT on a listenKey will extend its validity for 60 minutes.

How to do this by python?

**Comment by aisling-2** [comment]
https://github.com/binance/binance-connector-python/blob/master/binance/spot/_data_stream.py#L16

You can use this method to Ping/Keep-alive a ListenKey.
