### ISSUE TITLE
WebSocket connection closed: connection was closed uncleanly ("peer dropped the TCP connection without previous WebSocket closing handshake"), code: 1006, clean: False, reason: connection was closed uncleanly ("peer dropped the TCP connection without previous WebSocket closing handshake")

### ISSUE THREAD

**Issue by power-jun** [binance/binance-connector-python#221]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.

### Expected behaviour
Describe what should happen.

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python
* Python version
* Operating system

**Comment by 2pd** [comment]
Please provide more details, it can be better if you provide a script that can reproduce the issue.

**Comment by 2pd** [comment]
Please open a new issue if the problem is still happening on the latest version.
