### ISSUE TITLE
trailingDelta on create margin order

### ISSUE THREAD

**Issue by AngDrew** [binance/binance-connector-python#222]
Good day, guys!

Is there any option to use trailingDelta on margin orders?
I can't find it anywhere, and after reading very long documentation, 
I found that there's no trailingDelta parameter on the [Binance API margin order](https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-order-trade)

The only thing margin can have trailingDelta is using bapi/* endpoint, 
which I know by inspecting the network on Binance's margin trading. 
Still, I need help finding the documentation on the internet.

### Issue subject
trailingDelta is not a parameter on margin order

### Expected behavior
trailingDelta added to the margin order (cross and isolated)

### Actual behavior
trailingDelta is not a parameter on margin order

### Steps to reproduce
this order below is automatically converted to a stop limit order instead of a trailing stop. Oh, by the way, I use python-binance, not binance connector, but since this issue is still related to Binance API, I will post it here.

client.create_margin_order(
    symbol=symbol,
    side=SIDE_SELL,
    type=ORDER_TYPE_TAKE_PROFIT_LIMIT,
    #
    timeInForce=TIME_IN_FORCE_GTC,
    quantity=quantity,
    stopPrice=tp_price,
    price=tp_price,
    trailingDelta=td,
    # isolatedSymbol=symbol,
    # isIsolated=is_margin,
)

### Environment
Provide any relevant information about your setup, such as:
* Version of python-binance: 
* Python 3.10
* Operating system Mac OS Ventura 13.1

**Comment by 2pd** [comment]
Thank you for feedback. Trailing stop order is not supported on margin account.
Please check the official document at https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-order-trade
