### ISSUE TITLE
How to create a long entry ?

### ISSUE THREAD

**Issue by aymeric75** [binance/binance-connector-python#223]
I want to create a long entry, can we do this with the connector ?

In Pine it would be something like this:
`
strategy.entry("Enter Long", strategy.long, qty=transactionQty)`

The only piece of code I have found in the connector is this one:

```

# Post a new order
params = {
    'symbol': 'BTCUSDT',
    'side': 'BUY',
    'type': 'MARKET',
    'quantity': 0.0004,
}

response = client.new_order(**params)
```

But only buys and that's it... it does not take a long position per say.

Any idea ?

Thanks

**Comment by 2pd** [comment]
Are you trying to place a futures order? 
If so, please try this one https://github.com/binance/binance-futures-connector-python

**Comment by 2pd** [comment]
Please reopen if it's needed.
