### ISSUE TITLE
Klines for "1d" interval returns only 3 values

### ISSUE THREAD

**Issue by Leggerla** [binance/binance-connector-python#224]
### Issue subject
Klines for "1d" interval returns only 3 values. When I replace it with "1m" or "1s" all works fine (500 candles are returned).

### Expected behaviour
500 1-day candles should be returned

### Actual behaviour
3 candles are returned

### Steps to reproduce
symbol = 'BTCUSDT'
interval = '1d'
client.klines(symbol, interval)

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python : latest
* Python version: Python 3.9.16
* Operating system: Linux (on Google Colab)

**Comment by jonte-z** [comment]
Hi,

I am able to get 500+ klines return when using the same parameters as you. Can you make sure you're not using the Testnet `base_url`? When I use the Testnet URL, I only get Klines from 5th April onwards, however when I use the Live URL `(base_url="https://api.binance.com")` 500 Kline records are returned.

**Comment by Leggerla** [comment]
> Hi,
> 
> I am able to get 500+ klines return when using the same parameters as you. Can you make sure you're not using the Testnet `base_url`? When I use the Testnet URL, I only get Klines from 5th April onwards, however when I use the Live URL `(base_url="https://api.binance.com")` 500 Kline records are returned.

Yes, I use testnet. Why is there only data from 5th of April?

**Comment by 2pd** [comment]
The testnet reset data every month, that's why the 1d klines endpoint returns limit records.
