### ISSUE TITLE
Trailing Stop loss

### ISSUE THREAD

**Issue by aymeric75** [binance/binance-connector-python#225]
Hello,

I want to express this:

I want to start a BUY order when BTCUSDT is at 40k;

Then, if it grows even more of 0.1% (out of total BTCUSDT price, i.e around 29k) I want to start a trailing stop loss with an offset of 0.1% also (i.e., if the price goes down of 0.1% , the order will close, and if the price rises the trail will follow, always with a 0.1% distance from the actual price).

So, going through the documentation, and [some examples](https://github.com/binance/binance-spot-api-docs/blob/master/faqs/trailing-stop-faq.md), I found.

POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=40000&stopPrice=40040&trailingDelta=10&timestamp=<timestamp>&signature=<signature>'

Where 

which means that  : 

1) the order will start at 40k
2) the trailing will start after stopPrice is reached, ie after 40k+0.1% * 40k = 40040 is reached
3) if the price goes back down to 10 BIPS, ie 0.1%, then the order will close.

But actually, seeing at the exemples provided [here ](https://github.com/binance/binance-spot-api-docs/blob/master/faqs/trailing-stop-faq.md), I am not sure at all this is correct.

Thank you

**Comment by jonte-z** [comment]
Hi,

Yes what you have here is correct. The documentation page you linked is a good resource for demonstrating examples on how to use `trailingDelta`.

Also keep in mind that trailingDelta can only used with any of the following order types: STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT.
