### ISSUE TITLE
ModuleNotFoundError: No module named 'binance.websocket.spot.websocket_api'

### ISSUE THREAD

**Issue by Vincent-299** [binance/binance-connector-python#226]
### ModuleNotFoundError: No module named 'binance.websocket.spot.websocket_api'
pip install binance-connector.
Successfully installed autobahn-23.1.2 binance-connector-2.0.0 service-identity-21.1.0
When I tried the example of WebSocket, the ModuleNotFoundError was reported.
binance.websocket.spot.websocket_api and  binance.websocket.spot.websocket_stream were not found. SpotWebsocketClient of connector v1 and v2 is ok.

The codes are here:
from binance.websocket.spot.websocket_api import SpotWebsocketAPIClient # connector V3
from binance.websocket.spot.websocket_stream import SpotWebsocketStreamClient # connector V3
from binance.websocket.spot.websocket_client import SpotWebsocketClient # connector v1 and v2
import logging
import time

def message_handler(_, message):
    logging.info(message)

my_client = SpotWebsocketAPIClient(on_message=message_handler)

my_client.ticker(symbol="BNBBUSD", type="FULL")

time.sleep(5)
logging.info("closing ws connection")
my_client.stop()

### Actual behaviour
ModuleNotFoundError: No module named 'binance.websocket.spot.websocket_api'

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python --2.0.0
* Python version-- 3.7.13
* Operating system-- window10

**Comment by 2pd** [comment]
Please install the latest version; Websocket API is supported >= v3.x.x

**Comment by aisling-2** [comment]
@Vincent-299 @itayl2 

`binance-connector` is the official package in PyPI: https://pypi.org/project/binance-connector/3.0.0rc2/#history
(Don't use `binance-connector-python`)

At this moment, version 3 is at the pre-release stage, but can still be download by doing:
`pip uninstall binance-connector`
`pip install binance-connector --pre`

Once we're certain version 3 can be released as a stable version, you'll be able to get it normally with `pip install binance-connector`.
