### ISSUE TITLE
why websocket "EOF occurred in violation of protocol (_ssl.c:2393) "?

### ISSUE THREAD

**Issue by thecatshidog** [binance/binance-connector-python#229]
### Issue subject
websocket ：EOF occurred in violation of protocol (_ssl.c:2393)

### Expected behaviour
use SpotWebsocketAPIClient, wait 3minute, can throw this error

Because the following code is causing the problem 
```
except WebSocketException as e:
                if isinstance(e, WebSocketConnectionClosedException):
                    self.logger.error("Lost websocket connection")
                else:
                    self.logger.error("Websocket exception: {}".format(e))
                raise e
```

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
my code like this

```
while True:
    asyncio.sleep(1)
    client.klines(...)
    ......

```

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python 3.0.0rc1
* Python 3.11.0
* unbuntu 20

**Comment by 2pd** [comment]
can you provide script to reproduce?

thanks

**Comment by jmakov** [comment]
```python
import time

from binance.websocket.spot.websocket_stream import SpotWebsocketStreamClient

def message_handler(_, message):
    print(message)

my_client = SpotWebsocketStreamClient(on_message=message_handler)

# Subscribe to a single symbol stream
for symbol in ["cfxusdt", "stxusdt", "suiusdt", "usdcusdt", "busdusdt", "arbusdt", "eduusdt", "solusdt", "maticusdt", "rndrusdt", "btcusdt", "ethusdt", "bnbusdt", "xrpusdt", "adausdt", "dogeusdt", "ltcusdt", "xmrusdt", "etcusdt", "bchusdt"]:
    my_client.book_ticker(symbol=symbol)
    my_client.trade(symbol=symbol)
    my_client.partial_book_depth(symbol=symbol, level=20)
    my_client.diff_book_depth(symbol=symbol, speed=100)

    time.sleep(1)

while True:
    time.sleep(10)

my_client.stop()
```

**Comment by 2pd** [comment]
> 

What error did you see?

If client subscribe too many streams that it can't handle the data quick enough, the server could drop the connection.

**Comment by jmakov** [comment]
@2pd the error in the title - "EOF occurred in violation of protocol (_ssl.c:2393)". If you run my example above you get this error. And as you see, in the example we're doing noting with the received data.

**Comment by 2pd** [comment]
1. When you call `my_client = SpotWebsocketStreamClient(on_message=message_handler)`  this library build a websocket connection to the Binance Websocket server.

2. when you call

```python
    my_client.book_ticker(symbol=symbol)
    my_client.trade(symbol=symbol)
    my_client.partial_book_depth(symbol=symbol, level=20)
    my_client.diff_book_depth(symbol=symbol, speed=100)
```

It will send a subscribe message to each method on the symbol, for example
for `my_client.trade` method, it will send a 

```json
{"method": "SUBSCRIBE","params":["the_symbol_you_request@trade"],"id": xxxxxx}
```

json message to the server. 

When you call those messages in a for loop,  the client is sending 4 messages for each symbol, that 4x20=80 messages.

So you will very easily to be disconnected by reaching the websocket message limit, which is 5 message per IP per second.

https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#websocket-limits
