### ISSUE TITLE
What is the function for "Websocket BLVT NAV Kline/Candlestick Streams"

### ISSUE THREAD

**Issue by Vincent-299** [binance/binance-connector-python#231]
### Issue subject
There is  "Websocket BLVT NAV Kline/Candlestick Streams" in the following link:
https://binance-docs.github.io/apidocs/spot/en/#websocket-blvt-info-streams.

What is the function for "Websocket BLVT NAV Kline/Candlestick Streams"

**Comment by 2pd** [comment]
Sorry this is not supported in the library.
