### ISSUE TITLE
Websocket example in: "binance-connector-python/blob/master/examples/websocket/spot/websocket_stream/symbol_kline.py" doesn't work

### ISSUE THREAD

**Issue by hungson175** [binance/binance-connector-python#232]
### Issue subject
Example in: "binance-connector-python/blob/master/examples/websocket/spot/websocket_stream/symbol_kline.py" doesn't work

### Expected behaviour
Should print out stream of klines as expected

### Actual behaviour
Give out bug:
![image](https://user-images.githubusercontent.com/565789/236633058-adebe335-1e9d-4aa7-a83c-7ce6fe632395.png)

>__TypeError__: BinanceWebsocketClient.\__init__() got an unexpected keyword argument 'on_message'

### Steps to reproduce
After I install the binance-connector version "3.0.0.rc2" using command:
pip install binance-connector=="3.0.0.rc2"
and checked whether the basic API worked (in Dataspell) - well, it worked:

`
import logging
import time

from binance.spot import  Spot
import pandas as pd
import numpy as np
client = Spot()
pd.to_datetime(client.time()['serverTime'], unit='ms')
`

but the websocket example from following link printed out bug message:
[Example for websocket_stream/klines](https://github.com/binance/binance-connector-python/blob/master/examples/websocket/spot/websocket_stream/symbol_kline.py)

### Environment
Information
* Version of binance-connector-python: 3.0.0.rc2
* Python version: 3.10.9
* Operating system: Ubuntu 22.04.1 LTS
* IDE: Dataspell 2023.1.1 - with python interpreter: anaconda3

**Comment by jonte-z** [comment]
Hi there,

Can you please try reinstalling binance-connector-python==3.0.0rc2? Ideally with a fresh virtual environment. I just did that and ran the example and it's functioning as expected. See the below screenshot:
<img width="1717" alt="image" src="https://github.com/binance/binance-connector-python/assets/114036008/7dc35012-20c6-4698-bae5-2c914e0c53aa">
