### ISSUE TITLE
Convert getQuote endpoint not working

### ISSUE THREAD

**Issue by MidlightDDK** [binance/binance-connector-python#239]
Hey, sorry guys I think this is more a suggestion than an issue but I'm posting it here because I don't see any other place where I can post this.

So, my issue is the following: I want to use the endpoint "POST /sapi/v1/convert/getQuote" to convert crypto (different than buy/sell as far as I understood) but, there is no endpoint for this inside the Binance connector. When I realized that, I tried to make one myself by referring to this page [https://github.com/binance/binance-signature-examples/blob/master/python/spot/spot.py](https://github.com/binance/binance-signature-examples/blob/master/python/spot/spot.py) and I was able to make "manual requests" and I got the signature thingy right, but when I tried the "POST /sapi/v1/convert/getQuote" I got the following error:
`{'code': -1002, 'msg': 'You are not authorized to execute this request.'}`

I've tried a bunch of things but it looks like I have all the permissions on my API key and my IP is whitelisted.
![image](https://github.com/binance/binance-connector-python/assets/57988914/841a75de-f779-4764-a47e-5f18474c2142)

So, this brings me to the following questions:
Is the "POST /sapi/v1/convert/getQuote" endpoint missing from the Binance connector because it actually doesn't work?
If it works and I'm the only one facing the issue, what can I do to fix it?

Here is my test code for reference:

```
# Send quote request (USER_DATA)
params = {
    "fromAsset": "USDT",
    "toAsset": "BTC",
    "fromAmount": 11,
}
response = send_signed_request("POST", "/sapi/v1/convert/getQuote", params)
print(response)
```

**Comment by 2pd** [comment]
For convert endpoints:

> Please complete the [questionnaire](https://www.binance.com/en/survey/9b262810a04a4d00840e6ec1bb1425d4) to submit your request for access.

Please check the API document: https://binance-docs.github.io/apidocs/spot/en/#convert-endpoints
