### ISSUE TITLE
WebSocketConnectionClosedException: Connection to remote host was lost.

### ISSUE THREAD

**Issue by zooyl** [binance/binance-connector-python#240]
### Issue subject
Losing connection to websocket at random intervals

### Expected behaviour
Uninterrupted connection 

### Actual behaviour
I'm losing  connection to websocket at random intervals - 1hr, 4hr, 16hr after successful connection to binance.

### Environment
* binance-connector-python 3.1.0
* Python 3.11
* OS: ManjaroLinux 23.0.0

### Additional context
ListenKey is renewed every 15 minutes, and empty dict is returned without problems.
Connector v3 wss is being used.
on_error doesn't return anything which is normal behavior i assume cause the problem is websocket stream.
It happens on testnet (wss://testnet.binance.vision) and live environment (wss://stream.binance.com:9443)
I also logged and pinged google.com during this period and i didn't lose any packages when websocket error occurs

### Syntax error
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/binance/websocket/binance_socket_manager.py", line 61, in read_data
    op_code, frame = self.ws.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wojciech/trader/venv/lib/python3.11/site-packages/websocket/_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

```
### Installed packages
```
aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
backtrader==1.9.78.123
binance-connector==3.1.0
certifi==2023.5.7
charset-normalizer==3.1.0
contourpy==1.1.0
cycler==0.11.0
dateparser==1.1.8
fonttools==4.40.0
frozenlist==1.3.3
idna==3.4
kiwisolver==1.4.4
lxml==4.9.2
mailjet-rest==1.3.4
matplotlib==3.7.1
multidict==6.0.4
numpy==1.24.3
packaging==23.1
Pillow==9.5.0
pycryptodome==3.18.0
pyparsing==3.0.9
python-binance==1.0.17
python-dateutil==2.8.2
pytz==2023.3
regex==2023.6.3
requests==2.31.0
six==1.16.0
TA-Lib==0.4.26
tzlocal==5.0.1
ujson==5.8.0
urllib3==2.0.3
websocket-client==1.5.3
websockets==11.0.3
yarl==1.9.2
```

**Comment by lovedancer075** [comment]
Hi,  I met the same issue "websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.",   How to fix this?

**Comment by zooyl** [comment]
I've used this package last year with v2 version. I bumped ```websocket-client==1.5.3``` to latest ```1.6.1``` and got working it for 60hr. Didn't lose connection to remote host, but today at midnight i received following warning: ```2023-07-01 00:00:01.802 UTC WARNING binance.websocket.websocket_client: CLOSE frame received, closing websocket connection``` got to look into it

**Comment by taekop** [comment]
Same situation. I'd like to see this resolved urgently.

**Comment by zooyl** [comment]
After some testing and messing around, I found the issue is related to [websocket-client](https://github.com/websocket-client/websocket-client/issues/926) itself. As a workaround i installed old legacy v2 connector ```binance-connector==2.0.0``` which i've been using previously and isn't depending on ```websocket-client``` package. Can confirm my connection is up for 2 weeks straight already
