### ISSUE TITLE
How  to fix "Connection to remote host was lost" ?

### ISSUE THREAD

**Issue by lovedancer075** [binance/binance-connector-python#241]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
When I run app_demo.py (with very little modify, you can see the picture below),  I met a crash issue that "**websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.**"

Sometimes this error does not appear after running for tens of minutes, and sometimes this error occurs just after running...

### Steps to reproduce
run the example app_demo.py

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python   ---->  **binance-connector         3.1.0**
* Python version       ------>   **Python 3.9.0**
* Operating system   ---->    **Ubuntu 20.04.5 LTS**

![image](https://github.com/binance/binance-connector-python/assets/117306586/1820b269-fe2e-400d-a4e7-989aee8eda2d)

![image](https://github.com/binance/binance-connector-python/assets/117306586/68dd0b64-38f2-487f-a46e-231b5d19b954)

**Comment by artyomshutoff** [comment]
Have same issue.

code example:
https://gist.github.com/artyomshutoff/20d40c0c886486476dc44cd1635e0080

**Comment by zooyl** [comment]
@artyomshutoff Same issue, you can check out my [workaround](https://github.com/binance/binance-connector-python/issues/240#issuecomment-1695575577) for the time being, as it is dependency issue

**Comment by artyomshutoff** [comment]
> @artyomshutoff You can check out my [workaround](https://github.com/binance/binance-connector-python/issues/240#issuecomment-1695575577) for the time being, as it is dependency issue

Thank you!

**Comment by 2pd** [comment]
It seems I can make ws connection with the script provide.
Closing the ticket, please open a new ticket for any concern.

thanks

**Comment by sunshineinwater** [comment]
This error will appear at random time points, and it does not mean that the program cannot run normally. It may occur after 1 day or even 10 minutes after running.
