### ISSUE TITLE
How to set the leverage?

### ISSUE THREAD

**Issue by GGOSinon** [binance/binance-connector-python#243]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.

How to set the leverage?

### Expected behaviour
Describe what should happen.

Something like "client.set_leverage(5)"

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

There is no function to support this (Maybe I'm missing something?)

**Comment by 2pd** [comment]
I don't think there is a leverage setting for spot trading, please provide more details for better understanding.

**Comment by GGOSinon** [comment]
Yes you are right, I confused with future trades. Thanks!
