### ISSUE TITLE
binance.error.ParameterValueError: the enum value MAIN_ISOLATED_MARGIN is invalid

### ISSUE THREAD

**Issue by lifenglibao** [binance/binance-connector-python#250]
SDK version : binance_connector==3.1.1
SDK method : user_universal_transfer

Issue : TransferType missing MAIN_ISOLATED_MARGIN value

![image](https://github.com/binance/binance-connector-python/assets/6213184/9628d329-ffcb-4303-88d5-c28d33be0147)

**Comment by 2pd** [comment]
This has been fixed in the latest release. :)
