### ISSUE TITLE
weird warning msg from PyCharm IDE

### ISSUE THREAD

**Issue by leewi9** [binance/binance-connector-python#257]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject

So i found this warning from PyCharm, the code is copied from example folder.

![image](https://github.com/binance/binance-connector-python/assets/10832544/cd73e363-c475-4e4c-900c-35658a33aa9a)

![image](https://github.com/binance/binance-connector-python/assets/10832544/d92af08d-24ef-4004-b9c2-df4f6dd3cfef)

### Expected behaviour
Describe what should happen.

Should be no warnings.

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

Two warnings message happen, don't know why.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.

Pycharm new python file, and copy code from: examples/spot/market/depth.py

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python  v3.3.1
* Python version  3.11.4
* Operating system Windows 11
* Pycharm 2023.2.1

**Comment by 2pd** [comment]
that's strange, are you able to run the example files?

**Comment by leewi9** [comment]
> that's strange, are you able to run the example files?

Yes, it runs  perfectly ... just these warnings, out of nowhere ...

**Comment by 2pd** [comment]
Please open a new ticket if we can have more details related to the IDE.
