### ISSUE TITLE
Why ServerError doesn't contain error code like the ClientError does?

### ISSUE THREAD

**Issue by JINHAOHU** [binance/binance-connector-python#259]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
The ServerError object doesn't have a error code. I have to determine the type of error based on the error message. However, the error message will change over time.

### Expected behaviour
The ServerError should contain error code as well.

### Actual behaviour
The ServerError doesn't contain error code.

**Comment by 2pd** [comment]
For ServerError, there is no guarantee that server will return error code.  For example if there was an error of 500 returned, it means it's not expected by server side so there is no error code can be defined for that situation.  For server side error, the http status code is one of the main values that can used by clients to inspect.
