### ISSUE TITLE
logger parameter for SpotWebsocketAPIClient & SpotWebsocketStreamClient

### ISSUE THREAD

**Issue by LemonPepperSeasoning** [binance/binance-connector-python#260]
### Issue subject
SpotWebsocketAPIClient & SpotWebsocketStreamClient class does not take in `logger` parameter.

### Expected behaviour
SpotWebsocketAPIClient & SpotWebsocketStreamClient class take `logger` parameter, allowing developer to customize which logger these Classes should use. 

Please let me know if this was done on purpose. I would like to understand the thoughts behind this design. 

### Actual behaviour
As mentioned above, SpotWebsocketAPIClient & SpotWebsocketStreamClient class does not take in `logger` parameter making it hard for developer to customize logging configuration & debug problems. 

### Steps to reproduce
N/A

### Environment
N/A

### Example Solution
I believe solution is very simple. As described below, simply add a new parameter & pass it to the constructor of the parent class.
```python
class SpotWebsocketStreamClient(BinanceWebsocketClient):
    def __init__(
        self,
        stream_url="wss://stream.binance.com:9443",
        ...
        on_pong=None,
        logger=None, # new parameter
        is_combined=False,
        proxies: Optional[dict] = None,
    ):
        if is_combined:
            stream_url = stream_url + "/stream"
        else:
            stream_url = stream_url + "/ws"
        super().__init__(
            stream_url,
            ...
            on_ping=on_ping,
            on_pong=on_pong,
            logger=logger
            proxies=proxies,
        )
```

**Comment by 2pd** [comment]
Fixed in the latest release.

**Comment by LemonPepperSeasoning** [comment]
@2pd 
Cool! thanks 😄
