### ISSUE TITLE
How to handle connection timeout?

### ISSUE THREAD

**Issue by imanf94** [binance/binance-connector-python#266]
**WebSocket connection timed out!**

Everything works fine for short runs but since my app is supposed to work forever I lose connection to WebSocket after 1 or 2 days with a connection timeout exception! I'd like to handle connection timeout somehow. The timeout probably happened due to connection issues, but I couldn't catch the exception on my end. Can you let me know how to avoid a timeout exception raise by increasing the timeout length or creating a new WS connection?

UPDATE:
I found create_connection method in the binance_socket_manager and added timeout to the arguments as:
`self.ws = create_connection(self.stream_url, **self._proxy_params, timeout=10*60) # Max ping-pong wait = 10mins
`
I'm not sure if this is the right way to do this but I think it should work!

**Comment by 2pd** [comment]
timeout is supported in latest release. 
Thanks
