### ISSUE TITLE
New wallet endpoint for balances

### ISSUE THREAD

**Issue by AkshatGadhwal** [binance/binance-connector-python#267]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.
In the binance api change log 2023-09-22, a new endpoint for the wallet is added. 
```
GET /sapi/v1/asset/wallet/balance: query user wallet balance
```
There is not method in current binance-connector-python.

### Expected behaviour
Describe what should happen.
There can a method balances() for fetching balances from this sapi.

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.
see [change logs](https://binance-docs.github.io/apidocs/spot/en/#change-log) 2023-09-22 for the newly added wallet endpoint

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python
* Python version
* Operating system

**Comment by 2pd** [comment]
#272
