### ISSUE TITLE
Implement Message Buffering in WebSocket Manager

### ISSUE THREAD

**Issue by ben9809** [binance/binance-connector-python#277]
## Background:

Implementing message buffering in the WebSocket manager can offer various benefits, enhancing the system's resilience, fault tolerance, and overall performance. Below are the key technical reasons why this feature should be considered:

1. **Network Latency and Jitter:**
   - During high network activity, buffering prevents message loss due to latency or jitter.

2. **Temporary Unavailability of Consumers:**
   - Buffering helps handle scenarios where consumers are temporarily unable to process messages at the same rate as they arrive.

3. **Fluctuating Message Rates:**
   - Message buffering smoothens out fluctuations in message rates, ensuring stable performance during dynamic conditions.

4. **Preventing Data Loss During Connection Drops:**
   - Buffering safeguards messages sent during temporary disconnections, ensuring they are processed upon reconnection.

5. **Load Peaks and Troughs:**
   - The message buffer helps absorb peaks in incoming messages, preventing resource exhaustion during high loads.

6. **Enhancing Fault Tolerance:**
   - Buffering contributes to fault tolerance, maintaining message continuity during component downtimes and recoveries.

7. **Reducing Message Duplication:**
   - A message buffer with deduplication logic minimizes the impact of message duplication caused by retries or network issues.

8. **Optimizing Resource Utilization:**
   - Message buffering provides control over the message processing rate, preventing resource exhaustion in high-load scenarios.

9. **Smoother User Experience:**
   - For applications with user interfaces, buffering ensures a smoother user experience by retaining important updates even during delays.

10. **Facilitating Backpressure Mechanisms:**
    - Buffering supports the implementation of backpressure mechanisms to control the rate of incoming messages and prevent resource overuse.

## Benefits:

- Improved system resilience and fault tolerance.
- Prevention of message loss during network disruptions.
- Better handling of varying message rates and system loads.
- Enhanced user experience by reducing delays in message processing.

## Considerations:

- Define a suitable buffer size based on expected message rates and system requirements.
- Implement deduplication logic to handle duplicate messages.
- Provide methods for monitoring and retrieving messages from the buffer.

## Next Steps:

- Discuss the proposal.
- Gather feedback and additional requirements.

I look forward to hearing your thoughts about this feature!

**Comment by 2pd** [comment]
Thanks for the suggestion, however some of the features should not be implemented or at least I don't see it's reasonable.

1. This library should not buffer or store any outbound message, then resend for any reason ( e.g. reconnected). You won't like to see a market order to be sent again during the reconnection.   The library should act as a simple layer, don't do too much that make it over complicate.  Resend message or not should always be done by the user side, it's part of trading bot error handling or even the trade strategy itself.

2. I think the library should pass the incoming messages to clients as soon as possible. There is no reason to buffer.  If client can't handle the performance,  I would recommend to investigate better machine or tune the application.  I assume everyone want to receive the message as soon as possible.

Thanks
