### ISSUE TITLE
How disable logger in ws?

### ISSUE THREAD

**Issue by mcsham** [binance/binance-connector-python#280]
> [11:37:03] INFO [binance_client_protocol]         binance_client_protocol.py:40
> Received Ping from server                                                      
> [11:37:03] INFO [binance_client_protocol]         binance_client_protocol.py:42
> Responded Pong to server                                                       
> [11:37:04] INFO [binance_client_protocol] Server  binance_client_protocol.py:16
> connected                                                                      
> [11:37:04] INFO [binance_client_protocol] Sending binance_client_protocol.py:18
> message to Server: b'{"method": "SUBSCRIBE",                                   
> "params": ["fttusdt@kline_1h"], "id": 123}'                                    
> [11:37:04] INFO [binance_socket_manager]           binance_socket_manager.py:42
> Connection with URL: wss://fstream.binance.com/ws                              
> [11:37:04] INFO [binance_client_factory] Start to  binance_client_factory.py:23
> connect....   

how disable info logs in ws?

**Comment by 2pd** [comment]
It's not skip the INFO logs, however you could set the log level to WARNING to skip.

**Comment by mcsham** [comment]
It turned out that it is possible, but the solution is not the best and there is duplication of messages.
```
class CustomLogHandler(logging.Handler):
    def emit(self, record):
        if 'binance_' not in record.filename:
            print(self.format(record))
....
self.log.addHandler(CustomLogHandler())
```
