### ISSUE TITLE
Adding ID to "new_order / cancel_order and cancel_replace_order functions (WebsocketAPI)

### ISSUE THREAD

**Issue by souchy99** [binance/binance-connector-python#283]
### Issue subject
When I send multiple order at the same time (ex: 5 buy), when an error occur I can't know on which order exactly

### Expected behaviour
I would be able to define the "id" of the request, this would allow me to manage the error 

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
There is not really any step to reproduce the end goal is just to have add an id option as parameters of the functions : 
New_order
cancel_replace_order
and
cancel_order

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python last
* Python version 3.10
* Operating system Windows

**Comment by souchy99** [comment]
![image](https://github.com/binance/binance-connector-python/assets/102549728/28690a00-ad16-4f3b-b345-7cc0ac3706e7)

Whe i woud like, is either to get in return of the call of the function the random id generated, either be able to indicate him in the parameters

**Comment by souchy99** [comment]
I've added a fix in the pull request :) feel free to add it :)

**Comment by 2pd** [comment]
```python

my_client.new_order(
    id="websocket_api_1",
    symbol="BNBUSDT",
    side="BUY",
    type="LIMIT",
    timeInForce="GTC",
    quantity=1,
    price=200,
    newClientOrderId="my_order_id_1",
    newOrderRespType="RESULT",
)

```

You could pass your own id in the request.
