### ISSUE TITLE
[Docs] Outdated document

### ISSUE THREAD

**Issue by LemonPepperSeasoning** [binance/binance-connector-python#286]
I believe any reference (except for in a README where its the example is for older v1, v2 versions) to `SpotWebsocketClient` should be updated. (Afaik it has been refactored to `SpotWebsocketStreamClient` or `SpotWebsocketAPIClient`)

Do we care to update these doc listed below?

https://github.com/binance/binance-connector-python/blob/9209cfc729e365c803848cdfdb2d63daff1c27f6/docs/source/intro.rst?plain=1#L123

https://github.com/binance/binance-connector-python/blob/9209cfc729e365c803848cdfdb2d63daff1c27f6/docs/source/getting_started.rst?plain=1#L118

**Comment by 2pd** [comment]
Thanks we will get it updated.

**Comment by alplabin** [comment]
It has been updated in the latest release: https://github.com/binance/binance-connector-python/releases/tag/v3.7.0
