### ISSUE TITLE
Retrieving staking product list: I cannot find the examples.utils module

### ISSUE THREAD

**Issue by larry77** [binance/binance-connector-python#288]
Hello,
I run Debian stable and I have just installed (with pip) the binance-connector library.

`$ pip freeze | grep binance
binance-connector==3.5.1
`

I have already tried the first example at

https://github.com/binance/binance-connector-python/tree/master

and it works.
I would like to be able to retrieve the staked assets of my account, so I turned to

https://github.com/binance/binance-connector-python/blob/master/examples/spot/staking/staking_product_list.py

but here is what happens

`$ python3.11`
`Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
 `>>> import logging`
 `>>> from binance.spot import Spot as Client`
 `>>> from binance.lib.utils import config_logging`
 `>>> from binance.error import ClientError`
 `>>> from examples.utils.prepare_env import get_api_key`
 `Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
` ModuleNotFoundError: No module named 'examples.utils' `

any idea about how to fix this? My system just does not find the examples.utils module. Any help is appreciated!

**Comment by 2pd** [comment]
1. You could download the source code from this repository, then run the example file directly and it should work.
2. If you like to run it in your own script, please feel to set the api_key and api_secret manually.  `examples.utils.prepare_env` is not exposed in the library.
