### ISSUE TITLE
Change Binance Margin SAPI Endpoints (until 2024-03-31) due to disabling

### ISSUE THREAD

**Issue by DashaZhirenok** [binance/binance-connector-python#289]
### Issue subject
[Binance Margin](https://www.binance.com/en/margin-trading) will disable the following Margin SAPI endpoints at 2024-03-31 04:00 (UTC).

Announcement: https://www.binance.com/en/support/announcement/updates-on-binance-margin-sapi-endpoints-2024-03-31-a1868c686ce7448da8c3061a82a87b0c

### Expected behaviour
It will be great if you will update this API.

### Actual behaviour
In 3.5.1 version i see old margin API 

### Environment
* Version of binance-connector-python == 3.5.1
* Python version == 3.9
* Operating system == ubuntu 20.04

**Comment by alplabin** [comment]
These deprecated endpoints have been removed from the connector on the version `3.6.0`: https://github.com/binance/binance-connector-python/blob/master/CHANGELOG.md#360---2024-03-07
