### ISSUE TITLE
Staking Endpoints: WBETH related API

### ISSUE THREAD

**Issue by weitude** [binance/binance-connector-python#292]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Request for Staking Endpoints: WBETH related API

### Expected behaviour
In the `binance/spot/_staking.py` should have WBETH related API like https://binance-docs.github.io/apidocs/spot/en/#get-wbeth-rate-history-user_data

### Actual behaviour
No WBETH related API

### Steps to reproduce
N/A

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python: latest
* Python version: 3.11.6
* Operating system: M1 macOS

**Comment by alplabin** [comment]
They have been added in the latest version: https://github.com/binance/binance-connector-python/releases/tag/v3.10.0
