### ISSUE TITLE
Websocket connection exceptions are not handled by the user neither the on_error callback is called.

### ISSUE THREAD

**Issue by malvanos** [binance/binance-connector-python#293]
Websocket connection exceptions are not handled by the user neither the on_error callback is called.  It seems that there is a pull request for that #274. Can you please review it and accept it?

### Expected behaviour
Websocket connection errors should be handled by the on_error callback.

### Actual behaviour
The exception is raised inside the thread managing the websocket connection.

### Steps to reproduce
When closing the connection with any tool it will make the read to throw an exception.

### Environment
* Version of binance-connector-python: v3.6.0 
* Python version: 3.10.12

**Comment by MattGreeny** [comment]
Hey 👋 That PR has been open for a while and there seems to be no sign of it being merged. In case this helps you, I have been working from a fork with that change included and everything works great. I'm able to restart the websockets on errors/closes and it works perfectly, so I'd recommend doing the same if this helps you.

**Comment by alplabin** [comment]
The PR has been added to the version 3.7.0: https://github.com/binance/binance-connector-python/pull/315
