### ISSUE TITLE
Subscribe flexible product error

### ISSUE THREAD

**Issue by JasonKim001** [binance/binance-connector-python#300]
### Issue subject
Subscribe flexible product error

### Expected behaviour
Subscribe flexible product succeed

### Actual behaviour
api call error
![微信图片_20240312164302](https://github.com/binance/binance-connector-python/assets/29377930/1957a5b4-2c3c-4145-a232-dbaa9f0f759e)

### Steps to reproduce
call subscribe_flexible_product api

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python
* Python version
* Operating system

**Comment by alplabin** [comment]
The issue you're experiencing appears to be related to the region from which you're making the request, as mentioned in the error message.

Please review the 'Eligibility' section of the [Binance Terms of Service](https://www.binance.com/en/terms). Some regions or areas may have restrictions on accessing certain products or services. If you're making the request from the United States, you may want to consider using Binance.US instead.
