### ISSUE TITLE
ModuleNotFoundError: No module named 'binance'

### ISSUE THREAD

**Issue by myweb3world** [binance/binance-connector-python#304]
I use the [binance-connector-python](https://github.com/binance/binance-connector-python) in linux, but when I excute the 'python3 balance.py ', it occurs the error.
![微信截图_20240319181636](https://github.com/binance/binance-connector-python/assets/111629270/e82ca4ed-abe5-4da6-bc78-a2b989d0cd62)
when I install the package:
pip install binance-connector,
it occurs an error 'Unable to locate package binance-connector' or 'Unable to locate package binance-connector-python' or 'Unable to locate package binance'

**Comment by thisismygitrepo** [comment]
You're most probably installing in one environment and running in another

**Comment by aisling-2** [comment]
This is not a `binance-connector-python` lib issue, but a frequent local python environment misconfiguration that can only be solved by the user. However, some suggestions:
- See if the python version you've used to install our connector is the same one you're using to run the script. 
- See if the path where `binance` library was installed is the same one you're calling from. 

(Closing this issue as it's coming from the connector)
