### ISSUE TITLE
Exchange Info Websocket API incorrect data.

### ISSUE THREAD

**Issue by opusbogac** [binance/binance-connector-python#305]
Hello.
https://github.com/binance/binance-connector-python/blob/master/examples/websocket/spot/websocket_api/market/exchange_info.py
All the codes in this link return the data of all symbols, like the my_client.exchange.info() code. The code with symbol customization my_client.exchange_info(symbol="BNBBUSD") continues to return data for all symbols. Thanks

**Comment by opusbogac** [comment]
Also, the stop function in the link does not work properly. There is a constant flow of data.
https://github.com/binance/binance-connector-python/blob/master/examples/websocket/spot/websocket_stream/partial_book_depth.py
It's time for maintenance of Python libraries.

**Comment by opusbogac** [comment]
@trkzmn Ahmet bey python'da fazla ileri seviye değilim sanırım fonksiyonu döndürmenin manuel yolunu yazdınız fakat tam anlayamadım. Anlaşılır biçimde yazar mısınız?

**Comment by trkzmn** [comment]
Merhaba @opusbogac ,

exchange_info fonksiyonunda yer alan hatanın fonksiyondaki parametrenin verilmemesinden kaynaklandığını fark ederek pull request oluşturdum.  Bu pr ne zaman kabul edilir bilmiyorum. Şimdilik exchange_info fonksiyonunda yer alan bu hata ile karşılaşmadan fonksiyonu kullanmak istiyorsan izleyebileceğin 2 yöntem şu şekildedir;

    1- Manuel yöntem:
        binance-connector'ın kurulu olduğu klasörde alan binance/websocket/spot/websocket_api/_market.py adlı dosyayı açarak;
            ` payload = {"id": parameters.pop("id", get_uuid()), "method": "exchangeInfo"}`
        şeklindeki 226. satırı
            `payload = {"id": parameters.pop("id", get_uuid()), "method": "exchangeInfo", "params": parameters}`
        olarak değiştirmen yeterli olacaktır.

    2- Diğer yöntem:
        Terminalde aşağıda yer alan komutları sırası ile çalıştırmak.
        `pip3 uninstall binance-connector`
        `pip3 install git+https://github.com/trkzmn/binance-connector-python@master`

Saygılarımla,

**Comment by opusbogac** [comment]
Parametrelerin tanımlanmadığı açıktı fakat bunun kaynağını bulup gerekli düzenlemeyi yapmak, çok çok önemli bir tespit ve çalışma. Katkılarınızdan dolayı müteşekkirim. Sorun şuanda belirttiğiniz ilk yöntem ile çözülmüş durumda. Umarım bu pr'ı en kısa zamanda ekip uygular. Sağolun Ahmet bey.
Saygılarımla @trkzmn

**Comment by alplabin** [comment]
@opusbogac Thank you for pointing out the first issue. 
Regarding the second one, could you please give more details or share an example of the error you are encountering?

The script is designed to return a message every second for 10 seconds, resulting in a total of 10 messages. After testing, there doesn't appear to be any issues with the latest version of the script.
