### ISSUE TITLE
Is there any way to create a sub wallet deposit address via api

### ISSUE THREAD

**Issue by yy907668946** [binance/binance-connector-python#309]
I want to use api to create new deposit address but only get address supported.

**Comment by alplabin** [comment]
Hey,
Are you referring to creating a sub-account from an existing Binance account?

If so, you may want to consider using the [Sub-Account API](https://binance-docs.github.io/apidocs/spot/en/#sub-account-endpoints) accessible through the [Binance Connector Python library](https://github.com/binance/binance-connector-python/blob/master/binance/spot/_sub_account.py).

You can find examples on how to use the library [here](https://github.com/binance/binance-connector-python/tree/master/examples/spot/sub_account).
