### ISSUE TITLE
is there a way to modify the leverage in isolated margin, by default it's the maximum

### ISSUE THREAD

**Issue by swiinger** [binance/binance-connector-python#310]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
cannot modify the leverage in isolated margin

### Expected behaviour
there's not a method for isolated, there's one for cross : 
https://binance-docs.github.io/apidocs/spot/en/#adjust-cross-margin-max-leverage-user_data
Is it possible to modify the max leverage depending on the asset as it is manually possible on the website in margin isolated ?
thanks

**Comment by aisling-2** [comment]
Sorry but if there's no API endpoint for such, we can't include it in the library, so there's not much we can do here.
