### ISSUE TITLE
Renaming library.

### ISSUE THREAD

**Issue by thisismygitrepo** [binance/binance-connector-python#312]
Despite having different `install names`, both 

[binance-connector-python](https://github.com/binance/binance-connector-python)

& 

[binance-futures-connector-python](https://github.com/binance/binance-futures-connector-python)

have same name at `import time`, that is: `import binance`. Unfortunately, this name clash makes it virtually impossible to have the two libraries installed in the same environment.

Could you guys please communicate to reach any convenient solution for developers?

Thanks.

[Cross-referencing relevant issue](https://github.com/binance/binance-futures-connector-python/issues/179)

**Comment by alplabin** [comment]
Hey, 
As shown in the documentation, the way to import SPOT endpoints and FUTURES endpoints classes are different. If you encounter any issues, I suggest you follow the documentation:
- [SPOT](https://github.com/binance/binance-connector-python/blob/master/README.md#restful-apis) 
- [CM Futures](https://github.com/binance/binance-futures-connector-python/blob/main/README.md#restful-apis)
- UM Futures:
```
from binance.um_futures import UMFutures
```

**Comment by thisismygitrepo** [comment]
I can confirm that this works. 
Perhaps merging the two in one library is the way to go in the future.
Thanks

**Comment by Yuchun-Zhang** [comment]
> I can confirm that this works. Perhaps merging the two in one library is the way to go in the future. Thanks

agree. IMHO, merging into one would be much better for end users.
