### ISSUE TITLE
Add a condition to LIMIT order

### ISSUE THREAD

**Issue by R-S-M-A-N** [binance/binance-connector-python#313]
Hello,

This is not a BUG but an improvement request so I don't know if I should make the request here?

Currently when we place a LIMIT buy or sell order through the API the system works in "higher" or "equal" >= (For the "price" and the "cummulativeQuoteQty"), the "qty" remains fixed .
This generates sales at a loss...
I request the addition of a parameter in the request by the API to be able to specify the direction “less” or “equal” <= (For the "price" and the "cummulativeQuoteQty") while always keeping the "qty" fixed !!!

The ideal would be that by default the direction was >= and that as an option I could ask for <=

Maybe you can just create a FOKUP >= and a FOKDOWN <=

Can you do this please?

**Comment by alplabin** [comment]
I'm sorry, but these types of requests aren't related to the Python connector. I recommend posting your improvement on the Binance forum.
