### ISSUE TITLE
Support futures WS API

### ISSUE THREAD

**Issue by vaganov** [binance/binance-connector-python#314]
WS API is available for USD-M futures since 01.04.2024
https://binance-docs.github.io/apidocs/futures/en/#websocket-api

**Comment by alplabin** [comment]
Hey, 
This repository is intended for SPOT endpoints. For requests related to USD-M Futures, please refer to the following repository: https://github.com/binance/binance-futures-connector-python/tree/main

**Comment by vaganov** [comment]
Right you are, thanks!
