### ISSUE TITLE
Lack of Documentation.

### ISSUE THREAD

**Issue by IVTore** [binance/binance-connector-python#319]
### Issue subject
No Proper Websocket API and Websocket Stream API documentation.

### Expected behaviour
They should be clearly explained. We are blind dating with the API ;). 
Reading the source is not a very efficient solution.

### Actual behaviour
No documentation.

### Steps to reproduce
Just go to:
https://binance-connector.readthedocs.io/en/latest/binance.websocket.spot.html

### Environment
Not necessary

Thanks in advance for your work and interest.

**Comment by alplabin** [comment]
The documentation has been updated. You can have access to Websocket API and Websocket Stream API documentation now:
- Websocket API: https://binance-connector.readthedocs.io/en/latest/binance.spot.html
- Websocket Stream API: https://binance-connector.readthedocs.io/en/latest/binance.websocket_stream.spot.html
