### ISSUE TITLE
Display all the auto-invest transaction history 

### ISSUE THREAD

**Issue by Eliot4** [binance/binance-connector-python#320]
Hello everyone,

I would like to know if it is possible to pull all the transaction history of an auto-invest plan ? The code uploaded [here](https://github.com/binance/binance-connector-python/blob/master/examples/spot/auto_invest/query_subscription_transaction_history.py) can pull the latest transaction, does anyone know how to do it with all the transaction history based on the code above ? 

Thank you in advance !

**Comment by alplabin** [comment]
Hey,
According to the [documentation](https://binance-docs.github.io/apidocs/spot/en/#query-subscription-transaction-history-user_data), if you don't specify the `startTime` and `endTime` parameters, the endpoint will return data for the latest 30 days by default.

To retrieve all historical data, you can follow these steps:
1. Determine the starting date from which you need the data.
2. Set the `startTime` parameter to the beginning of the first 30-day interval.
3. Set the `endTime` parameter to the end of the same 30-day interval.
4. Make the API request with these `startTime` and `endTime` values.
5. Repeat steps 2-4, incrementing the `startTime` and `endTime` by 30-day intervals until you reach the current date.
