### ISSUE TITLE
The wrong path for the `import` WebSocket module in the documentation

### ISSUE THREAD

**Issue by vladiscripts** [binance/binance-connector-python#327]
### Issue subject
The documentation gives the wrong path for the `import` WebSocket module:
* https://binance-connector.readthedocs.io/en/latest/getting_started.html#websocket
* https://github.com/search?q=repo%3Abinance%2Fbinance-connector-python+binance.websocket.spot.websocket_client&type=code

```
from binance.websocket.spot.websocket_client import SpotWebsocketClient
```
There is no `spot.websocket_client` and `SpotWebsocketClient`.

### Expected behaviour
Update the doc.

### Actual behaviour
Error `ModuleNotFoundError: No module named 'binance.websocket.spot.websocket_client'`.

### Steps to reproduce
Copy the code example to Python and run.

### Environment
Provide any relevant information about your setup, such as:
* binance-connector 3.8.0
* Python 3.11
* Ubuntu 24.04

**Comment by alplabin** [comment]
The documentation on `readthedocs` has been [updated in v3.7.0](https://github.com/binance/binance-connector-python/commit/e16c0fdda3d26af3fff23ad2fc67a0e3a1ea4a1a#diff-c80ab28469bcd92d7e6482e75bed7f619b58a6a6b14f3df22ea9ae7592259c95) to reflect the current method for using the WebSocket. 

As for the `README` file, the line you mentioned refers to versions v1 and v2 of the connector, which used the WebSocket in this way. Therefore, there is no issue on that front.
