### ISSUE TITLE
Does this library handle “A single connection to the API is only valid for 24 hours; expect to be disconnected after the 24-hour mark.”?

### ISSUE THREAD

**Issue by JunyiXie** [binance/binance-connector-python#337]
https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api#general-api-information
> A single connection to the API is only valid for 24 hours; expect to be disconnected after the 24-hour mark.

I need to handle the 24H API disconnection when using this library?

**Comment by alplabin** [comment]
Hey, you'll need to handle it on your end.
