### ISSUE TITLE
Response headers not passed along if error cause is invalid JSON

### ISSUE THREAD

**Issue by nzjrs** [binance/binance-connector-python#343]
https://github.com/binance/binance-connector-python/blob/a49db79a78b0e71aae2f1861de5f69ec71f9cbb2/binance/api.py#L179

I see no reason why passing on the original response headers to `ClientError` - which is what id done in the other error path, is not the correct thing to do here.

Is this a simple typo, swapping the last and second-last arguments?

**Comment by alplabin** [comment]
Thanks for pointing out this. It has been updated in the [latest version](https://github.com/binance/binance-connector-python/releases/tag/v3.10.0).
