### ISSUE TITLE
[FeatureRequest] can we have an API that returns trading history

### ISSUE THREAD

**Issue by bigning** [binance/binance-connector-python#348]
Hi team, this is not a bug report, just a question or feature request. I trade a bunch of symbols, how can i just use 1 API call to return the recent trading history? The existing API like `margin_all_orders` needs `symbol` input, and returns history only for that symbol. Do we have an API that can return recent trades for all symbols?

**Comment by alplabin** [comment]
Hey, 
There is unfortunately no way to get all your recent trade history in 1 API call, the `symbol` parameter is mandatory.

**Comment by alplabin** [comment]
Since there are no APIs available on the [documentation](https://developers.binance.com/docs/margin_trading/Introduction) to address your issue, this feature request falls outside the scope of what this project offers.
