### ISSUE TITLE
What's the difference between BinanceWebsocketClient.live_subscribe and instant_subscribe?

### ISSUE THREAD

**Issue by Han-xox** [binance/binance-connector-python#68]
Do they just implement same function?

**Comment by 2pd** [comment]
`live_subscribe` is designed to be used by methods in child class `SpotWebsocketClient`, while `instant_subscribe` is for package users to subscribe with their own streams. This is very useful for a combined subscription.  See the usage example of  `symbol_ticker.py`

However, these 2 methods have no big difference, and can be merged together. We will change this in the next major version upgrade.

thanks for the feedback.

**Comment by Han-xox** [comment]
Thanks!
