### ISSUE TITLE
Trade websocket doesn't receive data (SSL error: certificate verify failed)

### ISSUE THREAD

**Issue by RepoUse** [binance/binance-connector-python#71]
When trying to run the [trade websocket example](https://github.com/binance/binance-connector-python/blob/master/examples/websocket/spot/trade.py), I always get the following message:
```
INFO:root:Connection with URL: wss://stream.binance.com:9443/ws
INFO:root:Start to connect....
WARNING:root:WebSocket connection closed: connection was closed uncleanly (SSL error: certificate verify failed (in tls_process_server_certificate)), code: 1006, clean: False, reason: connection was closed uncleanly (SSL error: certificate verify failed (in tls_process_server_certificate))
ERROR:root:Lost connection to Server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]. Retrying: 1
```

After that it tries again for four times and doesn't print any messages. All dependencies are installed. On the testnet it doesn't work neither.

Do you have any ideas how to solve it?

**Comment by aisling11** [comment]
Hi @RepoUse, can you check this closed issue with similar report?  https://github.com/binance/binance-connector-python/issues/57
