### ISSUE TITLE
Exchange Information - Add symbol as optional parameter

### ISSUE THREAD

**Issue by Ariwenie** [binance/binance-connector-python#84]
**New simple feature**

It would be helpfull to add optional symbol parameter for this:
https://binance-connector.readthedocs.io/en/latest/binance.spot.market.html#binance.spot.market.exchange_info

Original Binance API supports it so it only needs to pass it inside.
https://binance-docs.github.io/apidocs/spot/en/#exchange-information

Now default exchange_info() returns so much useless informations and you need filter it by symbol you looking for.
Its same situation like ticker_price() you can get prices of all symbols by ommiting parametr or simple one by providing it.

**Comment by chairz** [comment]
We will release this feature on the next version.

**Comment by chairz** [comment]
#85

**Comment by chairz** [comment]
merged into master, features will be up on the next release.
