### ISSUE TITLE
How to config proxy in websocket in the example

### ISSUE THREAD

**Issue by Tsunami-lj** [binance/binance-connector-python#89]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.
Currently，I can access https://api.binance.com succssfully, while unfortunately it fails when I intend to connect wss://stream.binance.com:9443

### Expected behaviour
Describe what should happen.
connect successfully

### Actual behaviour
Describe what happens instead. Please include the complete failure message.
ERROR:root:Can't connect to server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TCPTimedOutError'>: TCP connection timed out: 10060:

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.
run examples in websocket spot

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python
* Python version
* Operating system
Python 3.7.8
Windows10

**Comment by 2pd** [comment]
Connect to websocket with proxy is not supported.
